"use strict";

/**
 * HQ admin navigation model for BlessBoard V5 shell.
 * Enabled entries match live /hq routes; deferred Stitch modules are omitted.
 */

const HQ_ADMIN_NAV = Object.freeze([
  { key: "home",
    slot: "dashboard", label: "Dashboard", href: "/hq", icon: "dashboard", enabled: true, nav: true },
  // Admin Console rule: Website is second (after Dashboard).
  {
    key: "content",
    slot: "website",
    label: "Website",
    href: "/hq/website",
    icon: "language",
    enabled: true,
    nav: true,
  },
  {
    key: "branches",
    slot: "locations",
    label: "Branches",
    href: "/hq/branches",
    icon: "apartment",
    enabled: true,
    nav: true,
  },
  {
    key: "registrations",
    slot: "people",
    label: "Registrations",
    href: "/hq/registrations",
    icon: "how_to_reg",
    enabled: true,
    nav: true,
  },
  {
    key: "members",
    slot: "people",
    label: "Members",
    href: "/hq/members",
    icon: "badge",
    enabled: true,
    nav: true,
  },
  {
    key: "member-journey",
    slot: "people",
    label: "Member journey",
    href: "/hq/member-journey",
    icon: "route",
    enabled: true,
    nav: true,
  },
  {
    key: "staff-access",
    slot: "people",
    label: "Users",
    href: "/hq/settings/staff-access",
    icon: "group",
    enabled: true,
    nav: true,
  },
  {
    key: "roles",
    slot: "access",
    label: "Legacy permissions",
    href: "/hq/roles",
    icon: "security",
    enabled: true,
    nav: true,
  },
  {
    key: "settings",
    slot: "settings",
    label: "Settings",
    href: "/hq/settings",
    icon: "settings",
    enabled: true,
    nav: true,
  },
  {
    key: "broadcasts",
    slot: "content",
    label: "Broadcasts",
    href: "/hq/broadcasts",
    icon: "campaign",
    enabled: true,
    nav: true,
  },
  {
    key: "announcements",
    slot: "content",
    label: "Announcements",
    href: "/hq/announcements",
    icon: "newspaper",
    enabled: true,
    nav: true,
  },
  {
    key: "participation",
    slot: "operations",
    label: "Participation",
    href: "/hq/participation",
    icon: "groups",
    enabled: true,
    nav: true,
  },
  {
    key: "attendance",
    slot: "operations",
    label: "Attendance",
    href: "/hq/attendance",
    icon: "fact_check",
    enabled: true,
    nav: true,
  },
  {
    key: "giving",
    slot: "operations",
    label: "Giving",
    href: "/hq/giving",
    icon: "payments",
    enabled: true,
    nav: true,
  },
  {
    key: "resources",
    slot: "content",
    label: "Resources",
    href: "/hq/resources",
    icon: "menu_book",
    enabled: true,
    nav: true,
  },
  {
    key: "forms",
    slot: "content",
    label: "Forms",
    href: "/hq/forms",
    icon: "description",
    enabled: true,
    nav: true,
  },
  {
    key: "requests",
    slot: "operations",
    label: "Requests",
    href: "/hq/requests",
    icon: "inbox",
    enabled: true,
    nav: true,
  },
  {
    key: "reports",
    slot: "reports",
    label: "Reports",
    href: "/hq/reports",
    icon: "analytics",
    enabled: true,
    nav: true,
  },
  {
    key: "executive",
    slot: "reports",
    label: "Executive",
    href: "/hq/reports/executive",
    icon: "monitoring",
    enabled: true,
    nav: true,
    /** Network-only — omitted from shell when executive_reports is false. */
    requiresFeature: "executive_reports",
  },
  {
    key: "audit",
    slot: "reports",
    label: "Audit",
    href: "/hq/audit",
    icon: "history",
    enabled: true,
    nav: true,
  },
  {
    key: "governance",
    slot: "access",
    label: "Governance",
    href: "/hq/audit/governance",
    icon: "policy",
    enabled: true,
    nav: true,
    /** Network-only — omitted from shell when advanced_audit is false. */
    requiresFeature: "advanced_audit",
  },
  {
    key: "account",
    slot: "settings",
    label: "Account",
    href: "/hq/account",
    icon: "person",
    enabled: true,
    nav: true,
  },
]);

/** Mobile bottom tabs — shell-first, not every module. */
const HQ_ADMIN_MOBILE_TABS = Object.freeze(["home", "branches", "reports", "account"]);

module.exports = {
  HQ_ADMIN_NAV,
  HQ_ADMIN_MOBILE_TABS,
};
