"use strict";

const path = require("path");
const express = require("express");
const session = require("express-session");
const request = require("supertest");
const EventEmitter = require("events");

const test = require("node:test");
const assert = require("node:assert/strict");

function freshObsModule() {
  const p = path.join(__dirname, "..", "src", "lib", "fieldAgentAnalyticsObservability.js");
  delete require.cache[require.resolve(p)];
  return require(p);
}

test("observability: slow query logging triggers when threshold exceeded", async () => {
  process.env.FA_ANALYTICS_SLOW_QUERY_MS = "1";
  const obs = freshObsModule();
  const logs = [];
  const origWarn = console.warn;
  console.warn = (msg) => logs.push(String(msg));
  try {
    await obs.observeQuery(
      {
        query: "fieldAgentAnalytics.testQuery",
        obs: {
          endpoint: "/admin/field-agent-analytics/drilldown/submissions",
          tenant_id: 1,
          filters: { has_search: true },
        },
      },
      async () => {
        await new Promise((r) => setTimeout(r, 3));
        return { rows: [{ id: 1 }] };
      }
    );
  } finally {
    console.warn = origWarn;
  }
  assert.ok(logs.some((l) => l.includes('"type":"slow_query"')));
  assert.ok(logs.some((l) => l.includes('"query":"fieldAgentAnalytics.testQuery"')));
});

test("observability: endpoint timing logs generated by middleware", async () => {
  process.env.FA_ANALYTICS_SLOW_ENDPOINT_MS = "1";
  const obs = freshObsModule();
  const logs = [];
  const origWarn = console.warn;
  const origNow = Date.now;
  let fakeNow = 1000;
  Date.now = () => {
    fakeNow += 5;
    return fakeNow;
  };
  console.warn = (msg) => logs.push(String(msg));
  try {
    const mw = obs.endpointMiddleware();
    const req = {
      method: "GET",
      baseUrl: "/admin/field-agent-analytics",
      path: "/drilldown/submissions",
      session: { adminUser: { tenantId: 1 } },
    };
    const res = new EventEmitter();
    res.statusCode = 200;
    mw(req, res, function () {});
    res.emit("finish");
  } finally {
    console.warn = origWarn;
    Date.now = origNow;
  }
  assert.ok(logs.some((l) => l.includes('"type":"slow_endpoint"')));
  assert.ok(logs.some((l) => l.includes('"status":200')));
});

test("observability: error middleware logs failure safely", async () => {
  const obs = freshObsModule();
  const logs = [];
  const origErr = console.error;
  console.error = (msg) => logs.push(String(msg));
  try {
    const mw = obs.errorMiddleware();
    const req = {
      method: "GET",
      baseUrl: "/admin/field-agent-analytics",
      path: "/drilldown/submissions",
      session: { adminUser: { tenantId: 1 } },
    };
    const res = { statusCode: 500 };
    const err = new Error("boom");
    let nextCalled = false;
    mw(err, req, res, () => {
      nextCalled = true;
    });
    assert.equal(nextCalled, true);
  } finally {
    console.error = origErr;
  }
  assert.ok(logs.some((l) => l.includes('"type":"endpoint_error"')));
  assert.ok(logs.some((l) => l.includes('"error_name":"Error"')));
});

test("observability: filter summary does not log raw search text", async () => {
  const obs = freshObsModule();
  const summary = obs.summarizeFilters({
    q: "John 097...",
    status: "approved",
    from: "2026-01-01",
    to: "2026-01-31",
    agent: "5",
  });
  assert.equal(summary.has_search, true);
  assert.equal("q" in summary, false);
  assert.equal(summary.has_status, true);
});

test("observability instrumentation does not change endpoint output", async () => {
  const registerAdminFieldAgentAnalyticsRoutes = require("../src/routes/admin/adminFieldAgentAnalytics");
  const { ROLES } = require("../src/auth/roles");
  const app = express();
  app.set("view engine", "ejs");
  app.set("views", path.join(__dirname, "..", "views"));
  app.use(
    session({
      secret: "obs_route_test",
      resave: false,
      saveUninitialized: true,
      name: "obs_sid",
    })
  );
  app.use((req, res, next) => {
    req.session.adminUser = { id: 1, role: ROLES.TENANT_MANAGER, tenantId: 1 };
    res.locals.asset = () => "/styles.css";
    res.locals.bodyEmbedClass = "";
    res.locals.embed = false;
    next();
  });
  const router = express.Router();
  registerAdminFieldAgentAnalyticsRoutes(router);
  app.use("/admin", router);
  const res = await request(app)
    .get("/admin/field-agent-analytics/drilldown/submissions")
    .query({ bucket: "bad_bucket" })
    .expect(400);
  assert.equal(String(res.text || ""), "Invalid submissions drill-down bucket.");
});
