"use strict";

/**
 * Canonical Release Notes Center catalog (evidence-backed).
 * Status values must match the Release Notes Center taxonomy.
 * Do not invent PASS / RELEASED without repository evidence.
 */

const STATUS = Object.freeze({
  PLANNED: "PLANNED",
  IN_DEVELOPMENT: "IN DEVELOPMENT",
  IMPLEMENTED: "IMPLEMENTED",
  LOCAL_QA_PASS: "LOCAL QA PASS",
  HOSTED_QA_PASS: "HOSTED QA PASS",
  QA_BLOCKED: "QA BLOCKED",
  NOT_TESTED: "NOT TESTED",
  RELEASED: "RELEASED",
  UNVERIFIED: "UNVERIFIED",
  DOCUMENTATION_PENDING: "DOCUMENTATION PENDING",
});

const PRODUCTS = Object.freeze({
  BB: "BlessBoard",
  AC: "ActiveClinic",
  SHARED: "Shared GetPro Platform",
  INFRA: "Infrastructure",
});

/** @type {ReadonlyArray<string>} */
const VERSION_ORDER = Object.freeze(["1.0", "1.1", "1.2", "1.3", "2.0", "2.01", "2.02"]);

/**
 * @typedef {object} ReleaseFeature
 * @property {string} id
 * @property {string} name
 * @property {string} description
 * @property {string} workflow
 * @property {string} expectedBehavior
 * @property {string[]} products
 * @property {string} featureType
 * @property {string} implementationStatus
 * @property {string} qaStatus
 * @property {string[]} testCaseIds
 * @property {string[]} sources
 * @property {boolean} [publicSafe]
 */

/**
 * @typedef {object} ReleaseBug
 * @property {string} id
 * @property {string} severity
 * @property {string} product
 * @property {string} problem
 * @property {string|null} rootCause
 * @property {string|null} fix
 * @property {string} verificationStatus
 * @property {string[]} regressionTests
 * @property {string|null} outstanding
 * @property {string[]} sources
 * @property {boolean} [publicSafe]
 */

/**
 * @typedef {object} QaTestCase
 * @property {string} id
 * @property {string} featureOrBugId
 * @property {string} product
 * @property {string} objective
 * @property {string} prerequisites
 * @property {string[]} steps
 * @property {string} expectedResult
 * @property {string} status
 * @property {string} evidence
 */

/**
 * @typedef {object} ReleaseVersion
 * @property {string} version
 * @property {string} summary
 * @property {string|null} releaseDate
 * @property {string[]} products
 * @property {string} deploymentStatus
 * @property {string} qaVerification
 * @property {string[]} acceptanceCriteria
 * @property {string[]} pendingDevelopment
 * @property {string[]} knownIssues
 * @property {string[]} documentationGaps
 * @property {ReleaseFeature[]} features
 * @property {ReleaseBug[]} bugs
 * @property {QaTestCase[]} qaChecklist
 * @property {string[]} sources
 */

/** @type {ReadonlyArray<ReleaseVersion>} */
const VERSIONS = Object.freeze([
  Object.freeze({
    version: "1.0",
    summary:
      "ActiveClinic V1.0 release-candidate closure on branch V7 (testing). BlessBoard V5 foundation-era work is only partially mapped to the product label “1.0”; comprehensive unified 1.0 notes are incomplete.",
    releaseDate: "2026-08-26",
    products: [PRODUCTS.AC, PRODUCTS.BB, PRODUCTS.SHARED],
    deploymentStatus:
      "TESTING — ActiveClinic RC approved on moovex-platform-testing; production promotion was an explicit later operator step. Do not treat this label as verified production deployment.",
    qaVerification:
      "ACTIVECLINIC_V1_RELEASE_CANDIDATE_APPROVED (AC). BlessBoard 1.0 unified hosted closure: DOCUMENTATION PENDING.",
    acceptanceCriteria: [
      "AC FIX_REQUIRED 21-screen reconciliation closed or APPROVED_PRODUCT_DIFFERENCE",
      "Hosted SHA matches RC candidate on testing hosts",
      "Production untouched during RC closure",
    ],
    pendingDevelopment: [
      "Unified BlessBoard+ActiveClinic 1.0 release packet (DOCUMENTATION PENDING)",
    ],
    knownIssues: [
      "Historical docs use V5 / V7 branch labels; product “1.0” mapping for BlessBoard is incomplete",
    ],
    documentationGaps: [
      "No single docs/releases packet titled Version 1.0 covering both BB and AC",
      "BlessBoard 1.0 feature inventory for this center is UNVERIFIED / DOCUMENTATION PENDING",
    ],
    features: [
      Object.freeze({
        id: "F-1.0-AC-01",
        name: "ActiveClinic V1.0 release candidate",
        description:
          "Public booking/auth/CMS journeys certified against Stitch-scoped FIX_REQUIRED set (21 representative screens) with hosted QA on testing.",
        workflow:
          "Login → registration → public mini-site → CMS edit/publish on disposable QA clinic.",
        expectedBehavior:
          "Representative screens READY (≥95) or APPROVED_PRODUCT_DIFFERENCE; hosted journeys PASS on RC SHA.",
        products: [PRODUCTS.AC],
        featureType: "product_release",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-1.0-AC-01"],
        sources: [
          "docs/activeclinic/release/ACTIVECLINIC_V1_RELEASE_CANDIDATE_CLOSURE.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-1.0-BB-01",
        name: "BlessBoard V5 foundation (mapped to 1.0 label)",
        description:
          "BlessBoard V5 platform foundation / RC versioning existed historically; this Release Notes Center does not have a complete evidence-backed 1.0 feature matrix for BlessBoard.",
        workflow: "DOCUMENTATION PENDING",
        expectedBehavior: "DOCUMENTATION PENDING",
        products: [PRODUCTS.BB],
        featureType: "product_release",
        implementationStatus: STATUS.DOCUMENTATION_PENDING,
        qaStatus: STATUS.UNVERIFIED,
        testCaseIds: ["TC-1.0-BB-01"],
        sources: ["docs/release/V5_RELEASE_VERSIONING.md", "docs/release/V5_FINAL_RELEASE_APPROVAL.md"],
        publicSafe: true,
      }),
    ],
    bugs: [],
    qaChecklist: [
      Object.freeze({
        id: "TC-1.0-AC-01",
        featureOrBugId: "F-1.0-AC-01",
        product: PRODUCTS.AC,
        objective: "Confirm AC V1.0 RC hosted closure verdict",
        prerequisites: "Access to ACTIVECLINIC_V1_RELEASE_CANDIDATE_CLOSURE.md",
        steps: [
          "Open docs/activeclinic/release/ACTIVECLINIC_V1_RELEASE_CANDIDATE_CLOSURE.md",
          "Confirm verdict ACTIVECLINIC_V1_RELEASE_CANDIDATE_APPROVED",
          "Confirm production untouched",
        ],
        expectedResult: "Documented hosted RC approval on testing SHA b0c62cd4…",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/activeclinic/release/ACTIVECLINIC_V1_RELEASE_CANDIDATE_CLOSURE.md",
      }),
      Object.freeze({
        id: "TC-1.0-BB-01",
        featureOrBugId: "F-1.0-BB-01",
        product: PRODUCTS.BB,
        objective: "Locate complete BlessBoard 1.0 release notes",
        prerequisites: "Repository docs search",
        steps: ["Search docs for BlessBoard Version 1.0 unified release notes"],
        expectedResult: "Complete packet found — currently not found",
        status: STATUS.NOT_TESTED,
        evidence: "DOCUMENTATION PENDING",
      }),
    ],
    sources: [
      "docs/activeclinic/release/ACTIVECLINIC_V1_RELEASE_CANDIDATE_CLOSURE.md",
      "docs/release/V5_RELEASE_VERSIONING.md",
    ],
  }),

  Object.freeze({
    version: "1.1",
    summary:
      "No dedicated Version 1.1 release packet was found under docs/releases or docs/qa. Entries below are marked DOCUMENTATION PENDING / UNVERIFIED.",
    releaseDate: null,
    products: [PRODUCTS.BB, PRODUCTS.AC, PRODUCTS.SHARED],
    deploymentStatus: "UNVERIFIED — do not infer production deployment from missing docs",
    qaVerification: "DOCUMENTATION PENDING",
    acceptanceCriteria: ["DOCUMENTATION PENDING — establish historical 1.1 evidence pack"],
    pendingDevelopment: ["Author historical 1.1 release notes from git tags/commits if recovered"],
    knownIssues: ["Historical documentation gap for Version 1.1"],
    documentationGaps: [
      "No docs/releases/*1.1* or docs/qa/*1.1* release notes located",
    ],
    features: [
      Object.freeze({
        id: "F-1.1-GAP-01",
        name: "Version 1.1 historical inventory",
        description: "Feature inventory for 1.1 could not be reconstructed from release docs in-repo.",
        workflow: "DOCUMENTATION PENDING",
        expectedBehavior: "DOCUMENTATION PENDING",
        products: [PRODUCTS.SHARED],
        featureType: "documentation",
        implementationStatus: STATUS.DOCUMENTATION_PENDING,
        qaStatus: STATUS.UNVERIFIED,
        testCaseIds: ["TC-1.1-GAP-01"],
        sources: [],
        publicSafe: true,
      }),
    ],
    bugs: [],
    qaChecklist: [
      Object.freeze({
        id: "TC-1.1-GAP-01",
        featureOrBugId: "F-1.1-GAP-01",
        product: PRODUCTS.SHARED,
        objective: "Confirm absence of Version 1.1 release docs",
        prerequisites: "Repository checkout",
        steps: ["Search docs/releases and docs/qa for 1.1 release notes"],
        expectedResult: "Gap recorded as DOCUMENTATION PENDING",
        status: STATUS.NOT_TESTED,
        evidence: "Audit 2026-09-25 — no dedicated 1.1 packet",
      }),
    ],
    sources: [],
  }),

  Object.freeze({
    version: "1.2",
    summary:
      "No dedicated Version 1.2 product release packet was found. Related shared website morning QA packs exist but are not a certified 1.2 release note.",
    releaseDate: null,
    products: [PRODUCTS.BB, PRODUCTS.AC, PRODUCTS.SHARED],
    deploymentStatus: "UNVERIFIED",
    qaVerification: "DOCUMENTATION PENDING",
    acceptanceCriteria: ["DOCUMENTATION PENDING"],
    pendingDevelopment: ["Author historical 1.2 release notes if recovered from ops archives"],
    knownIssues: ["Historical documentation gap for Version 1.2"],
    documentationGaps: [
      "docs/platform/V1_WEBSITE_MORNING_QA_PACK.md exists but is not a Version 1.2 release note",
      "No certified 1.2 BB/AC release acceptance verdict located",
    ],
    features: [
      Object.freeze({
        id: "F-1.2-GAP-01",
        name: "Version 1.2 historical inventory",
        description: "Feature inventory for 1.2 could not be reconstructed from a dedicated release packet.",
        workflow: "DOCUMENTATION PENDING",
        expectedBehavior: "DOCUMENTATION PENDING",
        products: [PRODUCTS.SHARED],
        featureType: "documentation",
        implementationStatus: STATUS.DOCUMENTATION_PENDING,
        qaStatus: STATUS.UNVERIFIED,
        testCaseIds: ["TC-1.2-GAP-01"],
        sources: ["docs/platform/V1_WEBSITE_MORNING_QA_PACK.md"],
        publicSafe: true,
      }),
    ],
    bugs: [],
    qaChecklist: [
      Object.freeze({
        id: "TC-1.2-GAP-01",
        featureOrBugId: "F-1.2-GAP-01",
        product: PRODUCTS.SHARED,
        objective: "Confirm Version 1.2 documentation gap",
        prerequisites: "Repository checkout",
        steps: ["Search for Version 1.2 release notes"],
        expectedResult: "Gap recorded",
        status: STATUS.NOT_TESTED,
        evidence: "Audit 2026-09-25",
      }),
    ],
    sources: ["docs/platform/V1_WEBSITE_MORNING_QA_PACK.md"],
  }),

  Object.freeze({
    version: "1.3",
    summary:
      "V7 QA line labeled product Version 1.3 (About versionBase 1.03). September 2026 QA release notes plus BB/AC hosted closure packs. Joint freeze remained BLOCKED by BlessBoard draft-hydration Major.",
    releaseDate: "2026-09-20",
    products: [PRODUCTS.BB, PRODUCTS.AC, PRODUCTS.SHARED],
    deploymentStatus:
      "TESTING on moovex-platform-testing (pronline.org). Production remained on a different SHA and was untouched by freeze/closure work.",
    qaVerification:
      "AC hosted closure PASS; BB hosted closure FAIL; joint freeze V1_3_QA_FREEZE_BLOCKED. Not a full release PASS.",
    acceptanceCriteria: [
      "BB+AC hosted critical workflows PASS",
      "Automated regression green",
      "Draft hydration Major closed (not met at freeze)",
    ],
    pendingDevelopment: [
      "BlessBoard draft hydration Major (blocker at freeze SHA c5910e075aac)",
      "Section reorder / edit→public marker proof incomplete while hydration fails",
    ],
    knownIssues: [
      "BB About editor stays data-draft=0 under website_mode=draft after save/reload (Major)",
      "Recovery email delivery configuration pending on testing (not an app failure proof)",
    ],
    documentationGaps: [
      "Earlier Sep 5 V7 QA notes predate 1.3 freeze; treat as related historical evidence, not the freeze verdict",
    ],
    features: [
      Object.freeze({
        id: "F-1.3-AC-01",
        name: "ActiveClinic V1.3 hosted closure workflows",
        description:
          "Staff invitation, About image CDN publish, website section lifecycle certified on testing demo clinic.",
        workflow: "Login → staff activate → CMS draft/publish → public verify",
        expectedBehavior: "BUG-002/007/008 hosted PASS on documented SHA",
        products: [PRODUCTS.AC],
        featureType: "qa_closure",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-1.3-AC-01"],
        sources: ["docs/qa/V1_3_AC_QA_RELEASE_NOTES.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-1.3-SHARED-01",
        name: "Shared website governance + phone identity",
        description:
          "HQ-only publish authorization, cross-tenant denial, phone country/national split on registration.",
        workflow: "Finance cannot publish; cross-tenant 403; registration country list",
        expectedBehavior: "Governance and phone identity gates PASS on hosted BB probes",
        products: [PRODUCTS.SHARED, PRODUCTS.BB],
        featureType: "platform",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-1.3-SHARED-01"],
        sources: ["docs/qa/V1_3_BB_QA_RELEASE_NOTES.md", "docs/releases/V7_QA_RELEASE_NOTES_2026-09-05.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-1.3-AC-02",
        name: "ActiveClinic registration/media/editor reliability (Sep 5 pack)",
        description:
          "Phone validation hardening, media validation, CSRF publish fix, cache policy, network save/publish UX.",
        workflow: "Register / edit / publish under interruption scenarios",
        expectedBehavior: "Documented PASS items in V7_QA_RELEASE_NOTES_2026-09-05",
        products: [PRODUCTS.AC],
        featureType: "bugfix_pack",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-1.3-AC-02"],
        sources: ["docs/releases/V7_QA_RELEASE_NOTES_2026-09-05.md"],
        publicSafe: true,
      }),
    ],
    bugs: [
      Object.freeze({
        id: "BUG-1.3-BB-HYDRATION",
        severity: "Major",
        product: PRODUCTS.BB,
        problem:
          "About/home editor chrome stays data-draft=0 under website_mode=draft; saved drafts do not rehydrate after refresh.",
        rootCause: null,
        fix: null,
        verificationStatus: "OPEN",
        regressionTests: ["TC-1.3-BB-01"],
        outstanding: "Blocked V1_3_QA_FREEZE at SHA c5910e075aac",
        sources: ["docs/qa/V1_3_BB_QA_RELEASE_NOTES.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "BUG-1.3-EMPTY-BODY",
        severity: "Minor",
        product: PRODUCTS.SHARED,
        problem:
          "Empty body_text \"\" violated page_sections_body_text_len (23514) and historically surfaced as lookup_error on publish.",
        rootCause: "Empty string persisted instead of NULL for empty body",
        fix: "add/apply persist NULL instead of \"\" (shared website services)",
        verificationStatus: "MITIGATED — residual certification incomplete while hydration fails",
        regressionTests: ["TC-1.3-SHARED-02"],
        outstanding: "Full add→edit→public marker proof incomplete",
        sources: ["docs/qa/V1_3_BB_QA_RELEASE_NOTES.md"],
        publicSafe: true,
      }),
    ],
    qaChecklist: [
      Object.freeze({
        id: "TC-1.3-AC-01",
        featureOrBugId: "F-1.3-AC-01",
        product: PRODUCTS.AC,
        objective: "AC hosted closure BUG-002/007/008",
        prerequisites: "activeclinic.pronline.org testing",
        steps: ["Run hosted closure probes per V1_3_AC_QA_RELEASE_NOTES"],
        expectedResult: "V1_3_AC_HOSTED_CLOSURE_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V1_3_AC_QA_RELEASE_NOTES.md",
      }),
      Object.freeze({
        id: "TC-1.3-BB-01",
        featureOrBugId: "BUG-1.3-BB-HYDRATION",
        product: PRODUCTS.BB,
        objective: "BB draft hydration under website_mode=draft",
        prerequisites: "blessboard.pronline.org testing",
        steps: ["Add section / save / reload draft editor", "Observe data-draft"],
        expectedResult: "data-draft=1 and content hydrated",
        status: "OPEN",
        evidence: "docs/qa/V1_3_BB_QA_RELEASE_NOTES.md — FAIL on c5910e075aac",
      }),
      Object.freeze({
        id: "TC-1.3-SHARED-01",
        featureOrBugId: "F-1.3-SHARED-01",
        product: PRODUCTS.SHARED,
        objective: "Website governance hosted gate",
        prerequisites: "demo-church testing",
        steps: ["Finance publish denied", "HQ publish allowed"],
        expectedResult: "403 / published as documented",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V1_3_BB_QA_RELEASE_NOTES.md",
      }),
      Object.freeze({
        id: "TC-1.3-AC-02",
        featureOrBugId: "F-1.3-AC-02",
        product: PRODUCTS.AC,
        objective: "Sep 5 AC reliability pack",
        prerequisites: "V7 testing hosts",
        steps: ["Follow V7_QA_RELEASE_NOTES_2026-09-05 AC sections"],
        expectedResult: "Documented PASS items",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/releases/V7_QA_RELEASE_NOTES_2026-09-05.md",
      }),
      Object.freeze({
        id: "TC-1.3-SHARED-02",
        featureOrBugId: "BUG-1.3-EMPTY-BODY",
        product: PRODUCTS.SHARED,
        objective: "Empty body publish no longer 23514/lookup_error",
        prerequisites: "After NULL body fix deploy",
        steps: ["Add empty body section", "Publish"],
        expectedResult: "published without lookup_error on baseline probe",
        status: STATUS.NOT_TESTED,
        evidence: "Residual certification incomplete per V1_3_BB notes",
      }),
    ],
    sources: [
      "docs/qa/V1_3_BB_QA_RELEASE_NOTES.md",
      "docs/qa/V1_3_AC_QA_RELEASE_NOTES.md",
      "docs/releases/V7_QA_RELEASE_NOTES_2026-09-05.md",
    ],
  }),

  Object.freeze({
    version: "2.0",
    summary:
      "V8 platform line (neuniversity.org) introduced as Version 2.0 development/testing. Shared forms, membership, announcements, booking, and media work landed across overnight prompts. QA hub restricted to BB+AC V2.0 cards. About pages later moved to 2.01 — do not confuse hub marketing copy with About productVersion.",
    releaseDate: "2026-09-20",
    products: [PRODUCTS.BB, PRODUCTS.AC, PRODUCTS.SHARED],
    deploymentStatus:
      "TESTING — moovex-platform-v8-testing. Not an automatic production promotion. Production isolation preserved in V8 docs.",
    qaVerification:
      "V8_QA_HOMEPAGE_V2_ONLY_PASS for hub. Feature coverage is a mix of IMPLEMENTED / PARTIAL / hosted reports — not a single full release PASS.",
    acceptanceCriteria: [
      "V8 hub shows only BlessBoard V2.0 and ActiveClinic V2.0",
      "Production hosts untouched by V8 testing deploys",
      "Per-feature Stitch/workflow evidence recorded in V8_* docs",
    ],
    pendingDevelopment: [
      "Multiple PARTIAL Stitch mobile/desktop parity items in V8_IMPLEMENTATION_BASELINE",
      "Some V8 migrations created but not applied at baseline time",
    ],
    knownIssues: [
      "Implementation baseline PARTIAL rows (forms mobile, membership mobile, etc.)",
      "Historical BUG-002 shared deployment 503 and media delivery issues — see V8 bug docs",
    ],
    documentationGaps: [
      "No single “Version 2.0 RELEASED to production” certificate in-repo",
    ],
    features: [
      Object.freeze({
        id: "F-2.0-HUB-01",
        name: "V8 QA homepage Version 2.0 only",
        description:
          "neuniversity.org QA launcher shows BlessBoard V2.0 + ActiveClinic V2.0 only; V7 pronline hub unchanged.",
        workflow: "Open https://neuniversity.org/ → two product cards",
        expectedBehavior: "No V7 multi-product matrix on V8 hub",
        products: [PRODUCTS.SHARED],
        featureType: "platform",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.0-HUB-01"],
        sources: ["docs/releases/V8_QA_HOMEPAGE_VERSION_2_ONLY.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.0-FORMS-01",
        name: "Shared forms builder (SH01–SH15)",
        description:
          "Cross-product form studio, public submit, submission review — see implementation baseline statuses.",
        workflow: "Admin forms dashboard → studio → publish → public /f/:token → submissions",
        expectedBehavior: "Core flows IMPLEMENTED; some mobile Stitch PARTIAL",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "platform",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.UNVERIFIED,
        testCaseIds: ["TC-2.0-FORMS-01"],
        sources: ["docs/releases/V8_IMPLEMENTATION_BASELINE.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.0-BB-MEM-01",
        name: "BlessBoard membership workflows (BB01–BB18)",
        description: "Public apply wizard, activity registration, review queue, member profiles.",
        workflow: "Public register → HQ/branch review → member profile",
        expectedBehavior: "Most workflows IMPLEMENTED; several mobile PARTIAL",
        products: [PRODUCTS.BB],
        featureType: "product",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.UNVERIFIED,
        testCaseIds: ["TC-2.0-BB-MEM-01"],
        sources: ["docs/releases/V8_IMPLEMENTATION_BASELINE.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.0-AC-BOOK-01",
        name: "ActiveClinic booking / directory / services surfaces",
        description:
          "Directory navigation, service management, doctor profiles, booking inquiry prompts documented across V8_AC_* reports.",
        workflow: "Directory → clinic → book/inquire",
        expectedBehavior: "Per-prompt QA docs; aggregate status UNVERIFIED as a single release",
        products: [PRODUCTS.AC],
        featureType: "product",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.UNVERIFIED,
        testCaseIds: ["TC-2.0-AC-BOOK-01"],
        sources: [
          "docs/releases/V8_AC_DIRECTORY_NAVIGATION_QA.md",
          "docs/releases/V8_AC_SERVICE_MANAGEMENT_QA.md",
        ],
        publicSafe: true,
      }),
    ],
    bugs: [
      Object.freeze({
        id: "BUG-2.0-002-503",
        severity: "Critical",
        product: PRODUCTS.SHARED,
        problem: "Shared deployment 503 / boot failures documented in V8_BUG_002 and P0 root-cause docs.",
        rootCause: "See V8_P0_503_ROOT_CAUSE_AND_FIX.md / V8_BUG_002_SHARED_DEPLOYMENT_503.md",
        fix: "Documented remediation pack in those reports",
        verificationStatus: "See source docs — do not auto-declare RELEASED",
        regressionTests: ["TC-2.0-BUG-002"],
        outstanding: "Confirm hosted status from source doc before claiming PASS",
        sources: [
          "docs/releases/V8_BUG_002_SHARED_DEPLOYMENT_503.md",
          "docs/releases/V8_P0_503_ROOT_CAUSE_AND_FIX.md",
        ],
        publicSafe: true,
      }),
    ],
    qaChecklist: [
      Object.freeze({
        id: "TC-2.0-HUB-01",
        featureOrBugId: "F-2.0-HUB-01",
        product: PRODUCTS.SHARED,
        objective: "V8 hub Version 2.0 only",
        prerequisites: "neuniversity.org",
        steps: ["GET /", "Confirm only BB+AC V2.0 cards"],
        expectedResult: "V8_QA_HOMEPAGE_V2_ONLY_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/releases/V8_QA_HOMEPAGE_VERSION_2_ONLY.md",
      }),
      Object.freeze({
        id: "TC-2.0-FORMS-01",
        featureOrBugId: "F-2.0-FORMS-01",
        product: PRODUCTS.SHARED,
        objective: "Shared forms end-to-end on V8 testing",
        prerequisites: "BB or AC V8 host + forms migrations applied",
        steps: ["Create form", "Publish", "Submit", "Review"],
        expectedResult: "End-to-end PASS",
        status: STATUS.NOT_TESTED,
        evidence: "Aggregate hosted E2E not asserted as global PASS in this center",
      }),
      Object.freeze({
        id: "TC-2.0-BB-MEM-01",
        featureOrBugId: "F-2.0-BB-MEM-01",
        product: PRODUCTS.BB,
        objective: "Membership happy path on V8",
        prerequisites: "blessboard.neuniversity.org",
        steps: ["Public apply", "HQ review"],
        expectedResult: "Application reaches review queue",
        status: STATUS.NOT_TESTED,
        evidence: "Implementation baseline ≠ hosted release PASS",
      }),
      Object.freeze({
        id: "TC-2.0-AC-BOOK-01",
        featureOrBugId: "F-2.0-AC-BOOK-01",
        product: PRODUCTS.AC,
        objective: "Directory + booking smoke",
        prerequisites: "activeclinic.neuniversity.org",
        steps: ["Open directory", "Open clinic", "Start booking/inquiry"],
        expectedResult: "No 5xx on smoke path",
        status: STATUS.NOT_TESTED,
        evidence: "Per-prompt docs exist; center aggregate NOT TESTED",
      }),
      Object.freeze({
        id: "TC-2.0-BUG-002",
        featureOrBugId: "BUG-2.0-002-503",
        product: PRODUCTS.SHARED,
        objective: "Regression for shared deployment 503 class",
        prerequisites: "V8 testing healthz",
        steps: ["Check /healthz on hub + product hosts"],
        expectedResult: "200 ok schemaCompatible",
        status: STATUS.NOT_TESTED,
        evidence: "Re-verify against current tip before PASS",
      }),
    ],
    sources: [
      "docs/releases/V8_QA_HOMEPAGE_VERSION_2_ONLY.md",
      "docs/releases/V8_IMPLEMENTATION_BASELINE.md",
      "docs/releases/V8_HOSTED_END_TO_END_QA_REPORT.md",
    ],
  }),

  Object.freeze({
    version: "2.01",
    summary:
      "V8 tip labeled product Version 2.01. Shared website editor stack for BlessBoard + ActiveClinic: Change Manager, inline edit parity, image payload/placement, Universal Image Editor, section management, theme infra/gallery + first additional themes, HQ/branch website cards. Final integrated hosted QA 66/66 PASS; P2 gap closure 48/48 PASS. Not a production RELEASED certificate.",
    releaseDate: "2026-09-26",
    products: [PRODUCTS.BB, PRODUCTS.AC, PRODUCTS.SHARED, PRODUCTS.INFRA],
    deploymentStatus:
      "TESTING target moovex-platform-v8-testing. Shared editor features hosted-verified on V8. Production untouched in V2.01 task docs — do not promote.",
    qaVerification:
      "Shared website editor: HOSTED QA PASS (final integrated 66/66; P2 gaps 48/48). About + publish diagnostics HOSTED QA PASS. Hostinger Package A BLOCKED; worker consolidation UNVERIFIED. Not a full production RELEASED claim.",
    acceptanceCriteria: [
      "About shows 2.01 on BB+AC V8 testing after baseline deploy",
      "Publish failures no longer remapped to incorrect lookup_error",
      "Shared editor draft → preview → publish works on BB and AC without claiming unsupported Stitch-only surfaces",
      "AC facility websites and network-wide publish remain NOT SUPPORTED",
      "Infra Hostinger work tracked separately from application features",
    ],
    pendingDevelopment: [
      "Remaining Stitch theme packs beyond Contemporary Fellowship / Family Wellness Mint",
      "Palette / theme customizer (Stitch-only — not implemented)",
      "Stitch three-column HQ/branch studio (cards-only Choose Website is implemented)",
      "AC facility public websites / HQ→facility inheritance (explicitly NOT SUPPORTED)",
      "Network-wide / emergency publish (explicitly NOT SUPPORTED)",
      "Package A www worker retirement (operator hPanel)",
      "Hostinger PID consolidation proof",
      "Original intermittent Sep 24 publishing failure still not reproduced as a separate engine bug",
    ],
    knownIssues: [
      "Incomplete Hostinger log verification for original publish incident",
      "Remaining uncertainty around original intermittent publishing failure",
      "Package A BLOCKED (no hPanel access in agent session)",
      "Worker consolidation UNVERIFIED",
      "Stitch marketing mockups remain richer than CSS-pack alternate themes (visual gap, not functional defect)",
    ],
    documentationGaps: [
      "Stitch Release Notes Center screens: not present in Stitch project list (UI DOCUMENTATION PENDING vs approved Stitch)",
      "No dedicated V2.01 robots.txt change ticket found — existing SEO robots.txt is longer-standing platform capability",
    ],
    features: [
      Object.freeze({
        id: "F-2.01-ABOUT-01",
        name: "About page Version 2.01",
        description:
          "Shared applicationBuildInfo V8 productVersion/versionBase bumped to 2.01; BB and AC About consume buildInfo.",
        workflow: "Open /about on BB and AC V8 hosts",
        expectedBehavior: "Displays Version 2.01 / Release or Enterprise 2.01 with separate build SHA",
        products: [PRODUCTS.BB, PRODUCTS.AC, PRODUCTS.SHARED],
        featureType: "versioning",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-ABOUT-01"],
        sources: ["docs/releases/V2_01_RELEASE_BASELINE.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-ROBOTS-01",
        name: "robots.txt (platform SEO discovery)",
        description:
          "Tenant/clinic robots.txt via shared SEO discovery — existing capability. No dedicated V2.01 robots.txt change packet found; listed separately per task requirement.",
        workflow: "GET tenant/clinic /robots.txt",
        expectedBehavior: "Returns robots directives with sitemap when indexable",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "seo",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.UNVERIFIED,
        testCaseIds: ["TC-2.01-ROBOTS-01"],
        sources: ["src/platform/website/seoDiscovery.js", "tests/v7-shared-seo-expansion.test.js"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-PUB-DIAG-01",
        name: "Publish error diagnostics (real engine codes)",
        description:
          "BlessBoard publish catch-alls no longer mask failures as lookup_error. Returns publicCode/engineCode/requestId and friendly messages. AC explicit codes preserved.",
        workflow: "Trigger publish failure → observe code + request ID in UI/JSON",
        expectedBehavior: "Real classification codes; no secret leakage; successful multi-item publish still works",
        products: [PRODUCTS.BB, PRODUCTS.AC],
        featureType: "bugfix",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-PUB-DIAG-01", "TC-2.01-PUB-BB-01", "TC-2.01-PUB-AC-01"],
        sources: [
          "docs/qa/V2_01_PUBLISH_ERROR_DIAGNOSTICS_QA.md",
          "docs/qa/V2_01_PUBLISH_LOOKUP_ROOT_CAUSE.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-CM-FOUND-01",
        name: "Website Change Manager foundation",
        description:
          "Shared pending-change counting and Change Manager UI mounting infrastructure for BB+AC editors.",
        workflow: "Open website editor with drafts → pending count available to chrome",
        expectedBehavior: "Server-confirmed draft-vs-published distinct field counts",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "change_manager",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-CM-FOUND-01", "TC-2.01-EDITOR-FINAL-01"],
        sources: [
          "docs/qa/V2_01_CHANGE_MANAGER_FOUNDATION_QA.md",
          "docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-CM-TOOLBAR-01",
        name: "Editor toolbar + unpublished changes counter",
        description:
          "Shared editor chrome: pending pill, save status, History/Preview/Publish, Publish (N) badge.",
        workflow: "Edit fields → see pending count → Publish label updates",
        expectedBehavior: "Counts from server; save status honest; Publish gated by website.publish",
        products: [PRODUCTS.BB, PRODUCTS.AC],
        featureType: "change_manager",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-CM-TOOLBAR-01", "TC-2.01-EDITOR-FINAL-01"],
        sources: [
          "docs/qa/V2_01_TOOLBAR_REMINDERS_QA.md",
          "docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-CM-REMIND-01",
        name: "Friendly publishing reminders",
        description:
          "Reminder dialog at pending threshold (≥5) with Preview Changes / Keep Editing and don’t-show-again-today.",
        workflow: "Accumulate ≥5 unpublished fields → reminder",
        expectedBehavior: "Preview does not publish; dismissal website-scoped",
        products: [PRODUCTS.BB, PRODUCTS.AC],
        featureType: "change_manager",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-CM-REMIND-01"],
        sources: ["docs/qa/V2_01_TOOLBAR_REMINDERS_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-CM-PANEL-01",
        name: "Unpublished Changes Panel",
        description:
          "Panel listing unpublished fields with navigation back to editors; shared BB/AC infrastructure.",
        workflow: "Open unpublished panel from chrome → jump to field",
        expectedBehavior: "Lists server-confirmed pending fields only",
        products: [PRODUCTS.BB, PRODUCTS.AC],
        featureType: "change_manager",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-CM-PANEL-01"],
        sources: ["docs/qa/V2_01_UNPUBLISHED_CHANGES_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-CM-HIST-01",
        name: "Field-level history and restoration",
        description:
          "History beside pencil; restore from published versions + current draft tip; writes new draft revision for selected field; no auto-publish.",
        workflow: "History → choose version → restore field → pending count updates",
        expectedBehavior: "Never fabricates unavailable draft revisions; CDN media validated; expectedUpdatedAt conflicts honored",
        products: [PRODUCTS.BB, PRODUCTS.AC],
        featureType: "change_manager",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-CM-HIST-01", "TC-2.01-P2-GAPS-01"],
        sources: [
          "docs/qa/V2_01_FIELD_HISTORY_RESTORE_QA.md",
          "docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-CM-STITCH-01",
        name: "Change Manager Stitch mobile parity (~390px)",
        description:
          "CSS densification and layout checks against Website Change Manager Stitch screens for toolbar/reminder/panel/history.",
        workflow: "Resize editor chrome to ~390px",
        expectedBehavior: "Usable chrome without horizontal overflow for implemented screens",
        products: [PRODUCTS.BB, PRODUCTS.AC],
        featureType: "change_manager",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-CM-STITCH-01", "TC-2.01-P2-GAPS-01"],
        sources: [
          "docs/qa/V2_01_TOOLBAR_REMINDERS_QA.md",
          "docs/qa/V2_01_UNPUBLISHED_CHANGES_QA.md",
          "docs/qa/V2_01_FIELD_HISTORY_RESTORE_QA.md",
          "docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-BB-INLINE-01",
        name: "BlessBoard inline editor parity (WE01)",
        description:
          "BlessBoard public edit mode aligned to shared WE01 chrome: entry Manage/Preview/Edit, draft preview isolation, text/image dialogs, mobile framing.",
        workflow: "Open church public site with website_edit=1 → edit → preview → publish",
        expectedBehavior: "Shared editor chrome; draft not leaked live until publish",
        products: [PRODUCTS.BB, PRODUCTS.SHARED],
        featureType: "website_editor",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-BB-INLINE-01", "TC-2.01-EDITOR-FINAL-01"],
        sources: ["docs/qa/V2_01_BB_INLINE_EDITOR_PARITY_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-IMG-PAYLOAD-01",
        name: "Shared image object payload",
        description:
          "Draft/publish image fields accept structured {src,alt,mediaId,…} payloads with legacy string URL compatibility; unsafe URLs and foreign media rejected.",
        workflow: "Image dialog → library/upload → save draft → publish",
        expectedBehavior: "Object payload persisted; validation rejects javascript: and cross-tenant mediaId",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_editor",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-IMG-PAYLOAD-01"],
        sources: ["docs/qa/V2_01_SHARED_IMAGE_PAYLOAD_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-IMG-PLACE-01",
        name: "Shared image placement metadata",
        description:
          "Desktop/mobile focus and zoom placement stored as metadata; original CDN asset identity unchanged; invalid zoom/aspect overrides rejected.",
        workflow: "Adjust Picture → save → preview CSS vars → publish",
        expectedBehavior: "Placement CSS on draft/live; CDN src unchanged",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_editor",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-IMG-PLACE-01", "TC-2.01-P2-GAPS-01"],
        sources: [
          "docs/qa/V2_01_SHARED_IMAGE_PLACEMENT_QA.md",
          "docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-IMG-EDITOR-01",
        name: "Universal Image Editor",
        description:
          "Shared Adjust Picture / library / upload dialog for BB and AC image slots with desktop + ~390 framing modes.",
        workflow: "Open image pencil → upload or library → Adjust Picture → save",
        expectedBehavior: "Same shared editor chrome on BB and AC; placement persists across refresh",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_editor",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-IMG-EDITOR-01", "TC-2.01-P2-GAPS-01"],
        sources: [
          "docs/qa/V2_01_UNIVERSAL_IMAGE_EDITOR_QA.md",
          "docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-SECTION-01",
        name: "Shared section management",
        description:
          "Add Section picker and freeform/section actions on supported pages; collection pages keep structured editors without inventing unsupported Add Section.",
        workflow: "Edit mode → Add Section → draft appears → publish",
        expectedBehavior: "Draft-only until publish; unauthorized mutations denied",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_editor",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-SECTION-01"],
        sources: ["docs/qa/V2_01_SHARED_SECTION_MANAGEMENT_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-THEME-INFRA-01",
        name: "Shared website theme infrastructure",
        description:
          "Product-scoped theme registry + draft theme select API with cross-product rejection and public body theme attributes.",
        workflow: "GET/POST theme → draft preview → publish",
        expectedBehavior: "BB cannot select AC themes and vice versa; live theme unchanged until publish",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_theme",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-THEME-INFRA-01"],
        sources: ["docs/qa/V2_01_SHARED_THEME_INFRA_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-THEME-GALLERY-01",
        name: "Shared Choose Website Theme gallery",
        description:
          "Product-filtered theme gallery UI with current/draft indicators, Preview, and Select using theme infra APIs.",
        workflow: "Open gallery → preview alternate → select draft → publish",
        expectedBehavior: "Gallery lists only same-product themes; content not rewritten on select",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_theme",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-THEME-GALLERY-01"],
        sources: ["docs/qa/V2_01_SHARED_THEME_GALLERY_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-THEME-EXTRA-01",
        name: "First additional themes (BB + AC)",
        description:
          "Renderer-backed CSS packs: bb.contemporary-fellowship and ac.family-wellness-mint. Remaining Stitch theme packs and palette editor are NOT implemented.",
        workflow: "Gallery → select alternate → preview → publish → rollback to default",
        expectedBehavior: "Defaults preserved; content/section identities survive switch; cross-product rejected",
        products: [PRODUCTS.BB, PRODUCTS.AC, PRODUCTS.SHARED],
        featureType: "website_theme",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-THEME-EXTRA-01", "TC-2.01-EDITOR-FINAL-01"],
        sources: ["docs/qa/V2_01_FIRST_ADDITIONAL_THEMES_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-HQ-BRANCH-01",
        name: "HQ / branch website management (cards)",
        description:
          "Shared Choose Website card list: BB HQ + authorized branches reuse WE01 editor; AC shows exactly one clinic website. AC facility websites, three-column studio, and network-wide publish are NOT SUPPORTED.",
        workflow: "Website Management → choose card → Edit / View Live",
        expectedBehavior: "Authorized scopes only; AC no facility cards; HQ multi-site Change Website when applicable",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_scope",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-HQ-BRANCH-01", "TC-2.01-EDITOR-FINAL-01"],
        sources: ["docs/qa/V2_01_SHARED_HQ_BRANCH_WEBSITE_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-EDITOR-FINAL-01",
        name: "Shared website editor final integrated QA",
        description:
          "End-to-end hosted journey: draft → preview → publish, theme switch/rollback, HQ/branch cards, cross-product isolation, auth denials for BB and AC.",
        workflow: "Disposable V8 tenants · integrated hosted script",
        expectedBehavior: "66/66 hosted PASS on tip under test; production untouched",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_editor",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-EDITOR-FINAL-01"],
        sources: ["docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-P2-GAPS-01",
        name: "Shared editor P2 gap closure",
        description:
          "Hosted closure of residual P2 scenarios: image upload/library/Adjust Picture (desktop+390), field-history restore POST, structured item mutation (BB ministry + AC doctor).",
        workflow: "Browser + API harness on disposable BB/AC tenants",
        expectedBehavior: "48/48 hosted PASS; no application behavior change required for closure report tip",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_editor",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-P2-GAPS-01"],
        sources: ["docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-LIMITS-01",
        name: "Supported vs Stitch-only / unsupported surfaces",
        description:
          "Documented non-claims: AC facility websites, network-wide publish, remaining Stitch theme packs, palette editor, and three-column HQ/branch studio remain design-only or NOT SUPPORTED.",
        workflow: "Read release notes known limitations",
        expectedBehavior: "Operators do not treat Stitch-only or unsupported surfaces as available product features",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "documentation",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-LIMITS-01"],
        sources: [
          "docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md",
          "docs/qa/V2_01_SHARED_HQ_BRANCH_WEBSITE_QA.md",
          "docs/qa/V2_01_FIRST_ADDITIONAL_THEMES_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-INFRA-AUDIT-01",
        name: "Hostinger account-wide process audit (infra)",
        description:
          "Investigation of Node worker/PID topology on Hostinger account — infrastructure, not application functionality.",
        workflow: "Ops read-only probes",
        expectedBehavior: "Documented PID matrix and findings",
        products: [PRODUCTS.INFRA],
        featureType: "infrastructure",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.UNVERIFIED,
        testCaseIds: ["TC-2.01-INFRA-01"],
        sources: ["docs/qa/V2_01_HOSTINGER_PROCESS_AUDIT.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-INFRA-CONSOL-01",
        name: "Hostinger worker consolidation plan (infra)",
        description:
          "Plan/investigation whether multiple hostnames can share one Node PID. Application co-location already designed; Hostinger Topology A not demonstrated.",
        workflow: "Ops investigation only",
        expectedBehavior: "Findings documented; no false claim of PID merge",
        products: [PRODUCTS.INFRA],
        featureType: "infrastructure",
        implementationStatus: STATUS.PLANNED,
        qaStatus: STATUS.UNVERIFIED,
        testCaseIds: ["TC-2.01-INFRA-02"],
        sources: ["docs/qa/V2_01_HOSTINGER_WORKER_CONSOLIDATION_PLAN.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-INFRA-PKGA-01",
        name: "Hostinger Package A www retirement (infra)",
        description:
          "Retire dedicated www workers via Hostinger redirects + unbind. Not applied — agent lacked hPanel access.",
        workflow: "Operator hPanel redirects + unbind www from Node app",
        expectedBehavior: "Fewer warm hostnames/PIDs after operator change",
        products: [PRODUCTS.INFRA],
        featureType: "infrastructure",
        implementationStatus: STATUS.PLANNED,
        qaStatus: STATUS.QA_BLOCKED,
        testCaseIds: ["TC-2.01-INFRA-03"],
        sources: ["docs/qa/V2_01_HOSTINGER_PACKAGE_A_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.01-RNC-01",
        name: "Release Notes Center",
        description:
          "Permanent /release-notes center on the V8 platform QA hub and product apex hosts (BB + AC) with version routes, filters, QA checklists, share/print, and product-context defaults.",
        workflow: "Open /release-notes → filter → version detail → share/print",
        expectedBehavior: "Evidence-backed statuses; public vs internal separation; no invented PASS",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "platform",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.01-RNC-01"],
        sources: ["docs/releases/RELEASE_NOTES.md", "docs/qa/V2_01_RELEASE_NOTES_CENTER_QA.md"],
        publicSafe: true,
      }),
    ],
    bugs: [
      Object.freeze({
        id: "BUG-2.01-LOOKUP-REMAP",
        severity: "High",
        product: PRODUCTS.BB,
        problem:
          "BlessBoard publish catch-alls remapped many TX/engine failures to lookup_error, masking real codes.",
        rootCause:
          "Catch-all remapping in BB publish services (confirmed). Not proven as the sole cause of any specific Sep 24 intermittent failure.",
        fix: "websitePublishFailureDiagnostics + service catch path updates; requestId + publicCode",
        verificationStatus: "HOSTED QA PASS for diagnostics behavior; Hostinger log correlation incomplete",
        regressionTests: ["TC-2.01-PUB-DIAG-01", "TC-2.01-PUB-BB-01"],
        outstanding:
          "Original intermittent publishing failure not reproduced; Hostinger log verification incomplete",
        sources: [
          "docs/qa/V2_01_PUBLISH_LOOKUP_ROOT_CAUSE.md",
          "docs/qa/V2_01_PUBLISH_ERROR_DIAGNOSTICS_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "BUG-2.01-PKG-A",
        severity: "Medium",
        product: PRODUCTS.INFRA,
        problem: "www hostnames still warm distinct Node PIDs; Express 301 alone does not retire workers.",
        rootCause: "Hostinger per-vhost lsnode spawn; hPanel change required",
        fix: null,
        verificationStatus: "BLOCKED",
        regressionTests: ["TC-2.01-INFRA-03"],
        outstanding: "Operator Package A execution + before/after PID matrix",
        sources: ["docs/qa/V2_01_HOSTINGER_PACKAGE_A_QA.md"],
        publicSafe: true,
      }),
    ],
    qaChecklist: [
      Object.freeze({
        id: "TC-2.01-ABOUT-01",
        featureOrBugId: "F-2.01-ABOUT-01",
        product: PRODUCTS.SHARED,
        objective: "About shows 2.01 on V8 BB+AC",
        prerequisites: "moovex-platform-v8-testing deploy of baseline",
        steps: ["GET BB /about", "GET AC /about"],
        expectedResult: "Version 2.01 visible; V7 unchanged",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/releases/V2_01_RELEASE_BASELINE.md",
      }),
      Object.freeze({
        id: "TC-2.01-ROBOTS-01",
        featureOrBugId: "F-2.01-ROBOTS-01",
        product: PRODUCTS.SHARED,
        objective: "robots.txt responds on tenant/clinic",
        prerequisites: "Demo tenant on testing",
        steps: ["GET /robots.txt (tenant/clinic path)"],
        expectedResult: "200 with expected directives",
        status: STATUS.NOT_TESTED,
        evidence: "Unit coverage exists; V2.01 hosted recheck NOT TESTED",
      }),
      Object.freeze({
        id: "TC-2.01-PUB-DIAG-01",
        featureOrBugId: "F-2.01-PUB-DIAG-01",
        product: PRODUCTS.BB,
        objective: "Failure codes not remapped to lookup_error",
        prerequisites: "Diagnostics deploy on V8 testing",
        steps: ["Inject/classify failure paths", "Confirm publicCode"],
        expectedResult: "V2_01_PUBLISH_DIAGNOSTICS_QA_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_PUBLISH_ERROR_DIAGNOSTICS_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-PUB-BB-01",
        featureOrBugId: "F-2.01-PUB-DIAG-01",
        product: PRODUCTS.BB,
        objective: "BB multi-item publishing success on tip",
        prerequisites: "Disposable V8 QA church",
        steps: ["Edit multiple fields", "Publish"],
        expectedResult: "published success reported",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_PUBLISH_LOOKUP_ROOT_CAUSE.md § confirmed successful publish",
      }),
      Object.freeze({
        id: "TC-2.01-PUB-AC-01",
        featureOrBugId: "F-2.01-PUB-DIAG-01",
        product: PRODUCTS.AC,
        objective: "AC publishing success on tip",
        prerequisites: "Disposable V8 QA clinic",
        steps: ["Edit", "Publish"],
        expectedResult: "published success reported",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_PUBLISH_LOOKUP_ROOT_CAUSE.md",
      }),
      Object.freeze({
        id: "TC-2.01-CM-FOUND-01",
        featureOrBugId: "F-2.01-CM-FOUND-01",
        product: PRODUCTS.SHARED,
        objective: "Change Manager foundation + hosted pending counts",
        prerequisites: "V8 testing tip with editor chrome",
        steps: ["Run foundation tests", "Confirm pending count on hosted edit"],
        expectedResult: "V2_01_CHANGE_MANAGER_FOUNDATION_PASS + hosted pending reflected",
        status: STATUS.HOSTED_QA_PASS,
        evidence:
          "docs/qa/V2_01_CHANGE_MANAGER_FOUNDATION_QA.md; docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-CM-TOOLBAR-01",
        featureOrBugId: "F-2.01-CM-TOOLBAR-01",
        product: PRODUCTS.BB,
        objective: "Toolbar + counter hosted QA",
        prerequisites: "Disposable V8 church",
        steps: ["Verify pending pill and Publish (N)"],
        expectedResult: "Toolbar pending + Publish badge PASS hosted",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-CM-REMIND-01",
        featureOrBugId: "F-2.01-CM-REMIND-01",
        product: PRODUCTS.AC,
        objective: "Publishing reminder local/hosted QA",
        prerequisites: "≥5 pending fields",
        steps: ["Trigger reminder", "Preview does not publish"],
        expectedResult: "Reminder UX PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_TOOLBAR_REMINDERS_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-CM-PANEL-01",
        featureOrBugId: "F-2.01-CM-PANEL-01",
        product: PRODUCTS.SHARED,
        objective: "Unpublished panel QA",
        prerequisites: "Pending drafts",
        steps: ["Open panel", "Navigate to field"],
        expectedResult: "V2_01_UNPUBLISHED_CHANGES_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_UNPUBLISHED_CHANGES_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-CM-HIST-01",
        featureOrBugId: "F-2.01-CM-HIST-01",
        product: PRODUCTS.SHARED,
        objective: "Field history/restore hosted QA",
        prerequisites: "Published history available",
        steps: ["Restore field", "Confirm new draft revision", "Stale conflict 409"],
        expectedResult: "V2_01_FIELD_HISTORY_RESTORE_PASS + P2 restore PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence:
          "docs/qa/V2_01_FIELD_HISTORY_RESTORE_QA.md; docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-CM-STITCH-01",
        featureOrBugId: "F-2.01-CM-STITCH-01",
        product: PRODUCTS.SHARED,
        objective: "390px Change Manager / image framing chrome",
        prerequisites: "Hosted CSS",
        steps: ["Viewport 390px", "Inspect chrome + framing"],
        expectedResult: "No blocking overflow for implemented screens",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-BB-INLINE-01",
        featureOrBugId: "F-2.01-BB-INLINE-01",
        product: PRODUCTS.BB,
        objective: "BB inline WE01 parity hosted",
        prerequisites: "Disposable V8 church",
        steps: ["Open website_edit=1", "Edit text/image", "Preview", "Publish"],
        expectedResult: "V2_01_BB_INLINE_EDITOR_PARITY evidence PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_BB_INLINE_EDITOR_PARITY_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-IMG-PAYLOAD-01",
        featureOrBugId: "F-2.01-IMG-PAYLOAD-01",
        product: PRODUCTS.SHARED,
        objective: "Shared image object payload hosted",
        prerequisites: "BB+AC disposable tenants",
        steps: ["Save object payload", "Reject unsafe URL", "Reject foreign media"],
        expectedResult: "V2_01_SHARED_IMAGE_PAYLOAD_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_IMAGE_PAYLOAD_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-IMG-PLACE-01",
        featureOrBugId: "F-2.01-IMG-PLACE-01",
        product: PRODUCTS.SHARED,
        objective: "Image placement metadata hosted",
        prerequisites: "BB+AC disposable tenants",
        steps: ["Save placement", "Reject invalid zoom", "Publish CSS"],
        expectedResult: "V2_01_SHARED_IMAGE_PLACEMENT_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_IMAGE_PLACEMENT_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-IMG-EDITOR-01",
        featureOrBugId: "F-2.01-IMG-EDITOR-01",
        product: PRODUCTS.SHARED,
        objective: "Universal Image Editor hosted",
        prerequisites: "BB+AC disposable tenants",
        steps: ["Upload", "Library", "Adjust Picture desktop+390"],
        expectedResult: "V2_01_UNIVERSAL_IMAGE_EDITOR_PASS + P2 image PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence:
          "docs/qa/V2_01_UNIVERSAL_IMAGE_EDITOR_QA.md; docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-SECTION-01",
        featureOrBugId: "F-2.01-SECTION-01",
        product: PRODUCTS.SHARED,
        objective: "Shared section management hosted",
        prerequisites: "BB+AC disposable tenants",
        steps: ["Add Section", "Draft only until publish", "Auth deny"],
        expectedResult: "V2_01_SHARED_SECTION_MANAGEMENT_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_SECTION_MANAGEMENT_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-THEME-INFRA-01",
        featureOrBugId: "F-2.01-THEME-INFRA-01",
        product: PRODUCTS.SHARED,
        objective: "Theme infra product isolation hosted",
        prerequisites: "BB+AC disposable tenants",
        steps: ["Draft theme", "Cross-product 400", "Live unchanged until publish"],
        expectedResult: "V2_01_SHARED_THEME_INFRA_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_THEME_INFRA_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-THEME-GALLERY-01",
        featureOrBugId: "F-2.01-THEME-GALLERY-01",
        product: PRODUCTS.SHARED,
        objective: "Theme gallery product filter hosted",
        prerequisites: "BB+AC disposable tenants",
        steps: ["Open gallery", "Confirm product filter", "Select draft"],
        expectedResult: "V2_01_SHARED_THEME_GALLERY_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_THEME_GALLERY_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-THEME-EXTRA-01",
        featureOrBugId: "F-2.01-THEME-EXTRA-01",
        product: PRODUCTS.SHARED,
        objective: "First additional themes hosted",
        prerequisites: "BB+AC disposable tenants",
        steps: ["Select alternate", "Publish", "Rollback default"],
        expectedResult: "V2_01_FIRST_ADDITIONAL_THEMES_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_FIRST_ADDITIONAL_THEMES_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-HQ-BRANCH-01",
        featureOrBugId: "F-2.01-HQ-BRANCH-01",
        product: PRODUCTS.SHARED,
        objective: "HQ/branch website cards hosted",
        prerequisites: "BB HQ+branches + AC clinic",
        steps: ["List cards", "Edit scopes", "Confirm AC single clinic / no facilities"],
        expectedResult: "V2_01_SHARED_HQ_BRANCH_WEBSITE_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_HQ_BRANCH_WEBSITE_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-EDITOR-FINAL-01",
        featureOrBugId: "F-2.01-EDITOR-FINAL-01",
        product: PRODUCTS.SHARED,
        objective: "Final integrated editor hosted journey",
        prerequisites: "moovex-platform-v8-testing tip",
        steps: ["Run integrated hosted suite BB+AC"],
        expectedResult: "66/66 hosted PASS · V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA_PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md — 66/66 PASS",
      }),
      Object.freeze({
        id: "TC-2.01-P2-GAPS-01",
        featureOrBugId: "F-2.01-P2-GAPS-01",
        product: PRODUCTS.SHARED,
        objective: "P2 gap closure hosted",
        prerequisites: "moovex-platform-v8-testing tip",
        steps: ["Image upload/crop", "Field restore POST", "Structured mutate"],
        expectedResult: "48/48 hosted PASS · V2_01_SHARED_EDITOR_P2_GAPS_CLOSED",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md — 48/48 PASS",
      }),
      Object.freeze({
        id: "TC-2.01-LIMITS-01",
        featureOrBugId: "F-2.01-LIMITS-01",
        product: PRODUCTS.SHARED,
        objective: "Unsupported surfaces not claimed available",
        prerequisites: "Final + HQ/branch + themes QA docs",
        steps: [
          "Confirm AC facility websites NOT SUPPORTED",
          "Confirm network-wide publish NOT SUPPORTED",
          "Confirm remaining Stitch themes / palette / studio not implemented",
        ],
        expectedResult: "Limitations explicit in release notes",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md § Supported vs unsupported",
      }),
      Object.freeze({
        id: "TC-2.01-INFRA-01",
        featureOrBugId: "F-2.01-INFRA-AUDIT-01",
        product: PRODUCTS.INFRA,
        objective: "Process audit document complete",
        prerequisites: "Audit doc",
        steps: ["Review PID matrix"],
        expectedResult: "Findings recorded",
        status: STATUS.UNVERIFIED,
        evidence: "docs/qa/V2_01_HOSTINGER_PROCESS_AUDIT.md",
      }),
      Object.freeze({
        id: "TC-2.01-INFRA-02",
        featureOrBugId: "F-2.01-INFRA-CONSOL-01",
        product: PRODUCTS.INFRA,
        objective: "Worker consolidation feasibility",
        prerequisites: "Consolidation plan",
        steps: ["Confirm Topology A not demonstrated"],
        expectedResult: "V2_01_WORKER_CONSOLIDATION_UNVERIFIED",
        status: STATUS.UNVERIFIED,
        evidence: "docs/qa/V2_01_HOSTINGER_WORKER_CONSOLIDATION_PLAN.md",
      }),
      Object.freeze({
        id: "TC-2.01-INFRA-03",
        featureOrBugId: "F-2.01-INFRA-PKGA-01",
        product: PRODUCTS.INFRA,
        objective: "Package A applied",
        prerequisites: "hPanel operator",
        steps: ["Apply redirects", "Unbind www", "PID before/after"],
        expectedResult: "V2_01_PACKAGE_A_QA_PASS",
        status: "BLOCKED",
        evidence: "docs/qa/V2_01_HOSTINGER_PACKAGE_A_QA.md",
      }),
      Object.freeze({
        id: "TC-2.01-RNC-01",
        featureOrBugId: "F-2.01-RNC-01",
        product: PRODUCTS.SHARED,
        objective: "Release Notes Center routes on hub + BB + AC",
        prerequisites: "Deploy containing release-notes routes",
        steps: [
          "GET hub /release-notes",
          "GET blessboard /release-notes",
          "GET activeclinic /release-notes",
          "Confirm public sanitization + unauthorized internal deny",
        ],
        expectedResult: "200 HTML; product context; statuses match catalog; no secrets",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_RELEASE_NOTES_CENTER_QA.md; this update task",
      }),
    ],
    sources: [
      "docs/releases/V2_01_RELEASE_BASELINE.md",
      "docs/qa/V2_01_PUBLISH_ERROR_DIAGNOSTICS_QA.md",
      "docs/qa/V2_01_PUBLISH_LOOKUP_ROOT_CAUSE.md",
      "docs/qa/V2_01_CHANGE_MANAGER_FOUNDATION_QA.md",
      "docs/qa/V2_01_TOOLBAR_REMINDERS_QA.md",
      "docs/qa/V2_01_UNPUBLISHED_CHANGES_QA.md",
      "docs/qa/V2_01_FIELD_HISTORY_RESTORE_QA.md",
      "docs/qa/V2_01_BB_INLINE_EDITOR_PARITY_QA.md",
      "docs/qa/V2_01_SHARED_IMAGE_PAYLOAD_QA.md",
      "docs/qa/V2_01_SHARED_IMAGE_PLACEMENT_QA.md",
      "docs/qa/V2_01_UNIVERSAL_IMAGE_EDITOR_QA.md",
      "docs/qa/V2_01_SHARED_SECTION_MANAGEMENT_QA.md",
      "docs/qa/V2_01_SHARED_THEME_INFRA_QA.md",
      "docs/qa/V2_01_SHARED_THEME_GALLERY_QA.md",
      "docs/qa/V2_01_FIRST_ADDITIONAL_THEMES_QA.md",
      "docs/qa/V2_01_SHARED_HQ_BRANCH_WEBSITE_QA.md",
      "docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md",
      "docs/qa/V2_01_SHARED_EDITOR_P2_GAP_CLOSURE_QA.md",
      "docs/qa/V2_01_HOSTINGER_PROCESS_AUDIT.md",
      "docs/qa/V2_01_HOSTINGER_WORKER_CONSOLIDATION_PLAN.md",
      "docs/qa/V2_01_HOSTINGER_PACKAGE_A_QA.md",
      "docs/qa/V2_01_RELEASE_NOTES_CENTER_QA.md",
    ],
  }),

  Object.freeze({
    version: "2.02",
    summary:
      "V8 tip labeled product Version 2.02. Continues the shared WE01 website editor line with overnight SP-T1–T7 and U1-A–D polish, SP-VIS reminder/publish-failure UX, image placement + Universal Image Editor, theme gallery with alternate theme switching, BB HQ/branch website scope cards, and AC single-clinic website card. P1 blockers RC-MEDIA-PLACE and BB-THEME-503 fixed and retested 34/0/0 PASS on moovex-platform-v8-testing. Shared security and publish authorization PASS; AC booking FIXED_PASS. Not a production RELEASED certificate.",
    releaseDate: "2026-09-26",
    products: [PRODUCTS.BB, PRODUCTS.AC, PRODUCTS.SHARED],
    deploymentStatus:
      "TESTING target moovex-platform-v8-testing. Features listed below are hosted-verified on V8 testing. Production remains on older RC — do not treat this label as production promotion.",
    qaVerification:
      "P1 blocker retest HOSTED QA PASS (34/0/0). RC-MEDIA-PLACE PASS; BB-THEME-503 PASS. Shared security + publish authorization PASS. AC booking FIXED_PASS. Not a full production RELEASED claim.",
    acceptanceCriteria: [
      "About shows 2.02 on BB+AC V8 testing after deploy",
      "Release Notes Center lists version 2.02 for BlessBoard and ActiveClinic contexts",
      "P1 blockers RC-MEDIA-PLACE and BB-THEME-503 remain PASS on testing tip",
      "AC facility websites and network-wide publish remain NOT SUPPORTED",
      "No claim of production promotion, HOST-PKG-A closure, or backup verification",
    ],
    pendingDevelopment: [
      "Production RC promotion of placement + theme/websites packages",
      "HOST-PKG-A Hostinger www Node binding (ops — still blocked)",
      "BACKUP-PROD-VERIFY restore drill",
      "AC facility public websites / HQ→facility inheritance (NOT SUPPORTED)",
      "Remaining Stitch theme packs beyond Contemporary Fellowship / Family Wellness Mint",
      "Palette / theme customizer and three-column HQ/branch studio",
    ],
    knownIssues: [
      "Production RC still lacks placement + theme/websites until promote",
      "HOST-PKG-A remains BLOCKED_HOSTINGER_BACKEND",
      "Backup restore evidence UNKNOWN",
      "Stitch marketing mockups remain richer than CSS-pack alternate themes (visual gap)",
    ],
    documentationGaps: [
      "Production cutover packet for 2.02 not opened in this task",
    ],
    features: [
      Object.freeze({
        id: "F-2.02-ABOUT-01",
        name: "About page Version 2.02",
        description:
          "Shared applicationBuildInfo V8 productVersion/versionBase bumped to 2.02; BB and AC About consume buildInfo with separate Git build SHA.",
        workflow: "Open /about on BB and AC V8 hosts",
        expectedBehavior: "Displays Version 2.02 / Release or Enterprise 2.02 with separate build SHA",
        products: [PRODUCTS.BB, PRODUCTS.AC, PRODUCTS.SHARED],
        featureType: "versioning",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-ABOUT-01"],
        sources: ["docs/qa/V2_02_VERSION_RELEASE_NOTES_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-EDITOR-PARITY-01",
        name: "Shared WE01 editor parity (SP-T1–T7, U1-A–D)",
        description:
          "Shared BlessBoard + ActiveClinic website editor polish: SP-T1 through SP-T7 density/chrome work and U1-A through U1-D field history, unpublished panel, dialogs, and gallery surfaces — hosted-verified on V8 testing.",
        workflow: "Open website edit mode on BB and AC → exercise toolbar, history, panels, dialogs, gallery",
        expectedBehavior: "Shared chrome and SP/U1 surfaces usable on desktop and ~390px without claiming unsupported Stitch-only studios",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "website_editor",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-EDITOR-01"],
        sources: [
          "docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md",
          "docs/qa/V2_01_STITCH_PARITY_ACTION_PLAN.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-SP-VIS-01",
        name: "SP-VIS reminder / publish-failure UX",
        description:
          "Publishing reminder and publish-failure UX polish (SP-VIS) on the shared editor chrome.",
        workflow: "Accumulate pending changes → reminder; trigger publish failure → friendly failure surface",
        expectedBehavior: "Reminder does not publish; failure messaging remains honest without secret leakage",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "change_manager",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-SP-VIS-01"],
        sources: ["docs/qa/V2_01_SP_VIS_REMINDER_PUBFAIL_QA.md", "tests/v2-01-sp-vis-reminder-pubfail.test.js"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-IMG-PLACE-01",
        name: "Shared image placement + Universal Image Editor",
        description:
          "IMAGE values persist optional placement (fit/focal/zoom + optional mobile framing). Adjust Picture UI; CDN binary unchanged. RC-MEDIA-PLACE fixed and retested PASS on V8 testing.",
        workflow: "Edit hero image → Adjust Picture → save draft → preview → publish → public reload",
        expectedBehavior: "Placement CSS vars/data attrs persist; invalid zoom rejected; CDN URL unchanged",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "media",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-IMG-PLACE-01", "TC-2.02-P1-RETEST-01"],
        sources: [
          "docs/qa/V2_01_RC_MEDIA_PLACEMENT_FIX_QA.md",
          "docs/qa/V2_01_UNIVERSAL_IMAGE_EDITOR_QA.md",
          "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-THEME-01",
        name: "Theme gallery + alternate theme switching",
        description:
          "Product-filtered theme gallery with draft select, preview, publish, and rollback. Alternate packs: bb.contemporary-fellowship and ac.family-wellness-mint. BB-THEME-503 fixed (path routes + HQ aliases).",
        workflow: "Choose Theme → select alternate → preview draft → publish → restore default",
        expectedBehavior: "Gallery 200; HQ /hq/website/themes redirects to path; draft-only until publish",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "themes",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-THEME-01", "TC-2.02-P1-RETEST-01"],
        sources: [
          "docs/qa/V2_01_SHARED_THEME_GALLERY_QA.md",
          "docs/qa/V2_01_FIRST_ADDITIONAL_THEMES_QA.md",
          "docs/qa/V2_01_BB_THEME_503_FIX_QA.md",
          "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-BB-SCOPES-01",
        name: "BlessBoard HQ/branch website scope cards",
        description:
          "Choose Website list for authorized HQ and branch scopes; HQ apex /hq/website/websites aliases to path URL.",
        workflow: "Open /website/websites or /hq/website/websites as HQ admin",
        expectedBehavior: "Authorized scope cards; unauthorized denied; no AC facility websites claimed",
        products: [PRODUCTS.BB],
        featureType: "website_scopes",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-BB-SCOPES-01"],
        sources: [
          "docs/qa/V2_01_SHARED_HQ_BRANCH_WEBSITE_QA.md",
          "docs/qa/V2_01_BB_THEME_503_FIX_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-AC-SITE-01",
        name: "ActiveClinic single-clinic website card",
        description:
          "AC /website/websites lists the single authorized clinic site. Facility websites remain NOT SUPPORTED.",
        workflow: "Open clinic /website/websites as clinic admin",
        expectedBehavior: "Single clinic card; no multi-facility switcher",
        products: [PRODUCTS.AC],
        featureType: "website_scopes",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-AC-SITE-01"],
        sources: [
          "docs/qa/V2_01_SHARED_HQ_BRANCH_WEBSITE_QA.md",
          "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-P1-GATE-01",
        name: "P1 blocker fixes + retest (RC-MEDIA-PLACE, BB-THEME-503)",
        description:
          "V8 testing tip clears the two P1 product blockers: image placement persistence and BlessBoard theme/websites 503s. Hosted P1 blocker retest 34/0/0 PASS.",
        workflow: "Retest placement + theme gallery + websites on disposable V8 tenants",
        expectedBehavior: "Both blockers PASS; no AC regression on shared surfaces",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "release_gate",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-P1-RETEST-01"],
        sources: [
          "docs/qa/V2_01_P1_RELEASE_GATE_SUMMARY.md",
          "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-SEC-PUB-01",
        name: "Shared security and publish authorization",
        description:
          "Production-candidate security pack and publish authorization checks PASS (deny/CSRF/cross-tenant/session; allow/deny publish + forged ID).",
        workflow: "Exercise disposable BB/AC security and publish-auth matrices",
        expectedBehavior: "Unauthorized denied; authorized publish allowed; no forged-ID bypass",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "security",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-SEC-01"],
        sources: [
          "docs/qa/V2_01_PROD_SHARED_SECURITY_QA.md",
          "docs/qa/V2_01_PROD_PUBLISH_AUTH_QA.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-AC-BOOK-01",
        name: "ActiveClinic booking readiness (FIXED_PASS)",
        description:
          "AC booking wizard + inquiry + staff record verified FIXED_PASS on production-candidate pack; historical /book 400 treated as FIXED_VERIFIED design validation.",
        workflow: "Run booking readiness smoke on disposable AC tenant",
        expectedBehavior: "Wizard and inquiry complete; staff record created",
        products: [PRODUCTS.AC],
        featureType: "booking",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-AC-BOOK-01"],
        sources: ["docs/qa/V2_01_AC_BOOKING_READINESS_QA.md"],
        publicSafe: true,
      }),
      Object.freeze({
        id: "F-2.02-LIMITS-01",
        name: "Explicit non-claims for 2.02",
        description:
          "Does not claim production promotion, HOST-PKG-A closure, backup verification, AC facility websites, extra theme packs beyond the two alternate CSS packs, or deferred backlog items.",
        workflow: "Read release notes pending/known sections",
        expectedBehavior: "Limitations explicit; no invented RELEASED-to-production status",
        products: [PRODUCTS.SHARED, PRODUCTS.BB, PRODUCTS.AC],
        featureType: "documentation",
        implementationStatus: STATUS.IMPLEMENTED,
        qaStatus: STATUS.HOSTED_QA_PASS,
        testCaseIds: ["TC-2.02-LIMITS-01"],
        sources: ["docs/qa/V2_02_VERSION_RELEASE_NOTES_QA.md"],
        publicSafe: true,
      }),
    ],
    bugs: [
      Object.freeze({
        id: "BUG-2.02-RC-MEDIA-PLACE",
        severity: "P1",
        product: PRODUCTS.SHARED,
        problem:
          "Image placement metadata stripped on production RC and was absent from early V8 RC tip (RC-MEDIA-PLACE).",
        rootCause: "imagePlacement validator/persistence not on RC 03a89106e2fe",
        fix: "Placement stack on V8 tip + promotion branch v2-01-rc-media-placement; hosted retest PASS",
        verificationStatus: STATUS.HOSTED_QA_PASS,
        regressionTests: ["TC-2.02-IMG-PLACE-01", "TC-2.02-P1-RETEST-01"],
        outstanding: "Production remain blocked until promote",
        sources: [
          "docs/qa/V2_01_RC_MEDIA_PLACEMENT_FIX_QA.md",
          "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
        ],
        publicSafe: true,
      }),
      Object.freeze({
        id: "BUG-2.02-BB-THEME-503",
        severity: "P1",
        product: PRODUCTS.BB,
        problem:
          "BlessBoard theme gallery and websites routes returned 503 Unavailable on stale RC; HQ apex aliases also missing on tip.",
        rootCause: "Stale RC missing theme/websites routes; HQ /hq/website/themes|websites unwired",
        fix: "Theme gallery on tip + HQ 303 aliases (c446f469); promotion branch v2-01-rc-bb-theme-503; retest PASS",
        verificationStatus: STATUS.HOSTED_QA_PASS,
        regressionTests: ["TC-2.02-THEME-01", "TC-2.02-P1-RETEST-01"],
        outstanding: "Production remain blocked until promote",
        sources: [
          "docs/qa/V2_01_BB_THEME_503_FIX_QA.md",
          "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
        ],
        publicSafe: true,
      }),
    ],
    qaChecklist: [
      Object.freeze({
        id: "TC-2.02-ABOUT-01",
        featureOrBugId: "F-2.02-ABOUT-01",
        product: PRODUCTS.SHARED,
        objective: "About shows 2.02 on V8 BB+AC",
        prerequisites: "Deploy with VERSION_BASE_V8=2.02",
        steps: ["GET blessboard /about", "GET activeclinic /about"],
        expectedResult: "Version 2.02 visible; build SHA separate; V7 unchanged",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_02_VERSION_RELEASE_NOTES_QA.md",
      }),
      Object.freeze({
        id: "TC-2.02-EDITOR-01",
        featureOrBugId: "F-2.02-EDITOR-PARITY-01",
        product: PRODUCTS.SHARED,
        objective: "SP-T1–T7 and U1-A–D editor parity present",
        prerequisites: "V8 testing tip with overnight editor work",
        steps: ["Open BB+AC edit mode", "Spot-check toolbar/history/panel/dialogs/gallery"],
        expectedResult: "Surfaces load; no claim of unsupported studio",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_SHARED_WEBSITE_EDITOR_FINAL_QA.md",
      }),
      Object.freeze({
        id: "TC-2.02-SP-VIS-01",
        featureOrBugId: "F-2.02-SP-VIS-01",
        product: PRODUCTS.SHARED,
        objective: "SP-VIS reminder/publish-failure UX",
        prerequisites: "Editor with pending changes",
        steps: ["Trigger reminder", "Observe publish-failure copy"],
        expectedResult: "Friendly UX without secrets",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "tests/v2-01-sp-vis-reminder-pubfail.test.js",
      }),
      Object.freeze({
        id: "TC-2.02-IMG-PLACE-01",
        featureOrBugId: "F-2.02-IMG-PLACE-01",
        product: PRODUCTS.SHARED,
        objective: "Placement persists BB+AC",
        prerequisites: "Disposable tenants",
        steps: ["Upload", "Save placement", "Publish", "Public check"],
        expectedResult: "Placement PASS both products",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
      }),
      Object.freeze({
        id: "TC-2.02-THEME-01",
        featureOrBugId: "F-2.02-THEME-01",
        product: PRODUCTS.BB,
        objective: "Theme gallery + alternate switch",
        prerequisites: "BB HQ disposable",
        steps: ["Open themes", "Select alternate", "Preview", "Restore default"],
        expectedResult: "No 503; draft select works",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
      }),
      Object.freeze({
        id: "TC-2.02-BB-SCOPES-01",
        featureOrBugId: "F-2.02-BB-SCOPES-01",
        product: PRODUCTS.BB,
        objective: "HQ/branch website cards",
        prerequisites: "BB HQ disposable",
        steps: ["GET /website/websites", "GET /hq/website/websites"],
        expectedResult: "200 cards; HQ alias 303",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
      }),
      Object.freeze({
        id: "TC-2.02-AC-SITE-01",
        featureOrBugId: "F-2.02-AC-SITE-01",
        product: PRODUCTS.AC,
        objective: "AC single clinic website card",
        prerequisites: "AC admin disposable",
        steps: ["GET /clinics/:key/website/websites"],
        expectedResult: "200 single-clinic card",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
      }),
      Object.freeze({
        id: "TC-2.02-P1-RETEST-01",
        featureOrBugId: "F-2.02-P1-GATE-01",
        product: PRODUCTS.SHARED,
        objective: "P1 blocker retest CLEAR on testing tip",
        prerequisites: "Tip with placement + theme fixes",
        steps: ["Run P1 blocker retest harness"],
        expectedResult: "34/0/0; RC-MEDIA-PLACE PASS; BB-THEME-503 PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
      }),
      Object.freeze({
        id: "TC-2.02-SEC-01",
        featureOrBugId: "F-2.02-SEC-PUB-01",
        product: PRODUCTS.SHARED,
        objective: "Security + publish-auth PASS",
        prerequisites: "Disposable prod/testing packs",
        steps: ["Review security pack", "Review publish-auth pack"],
        expectedResult: "Both PASS",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_PROD_SHARED_SECURITY_QA.md; docs/qa/V2_01_PROD_PUBLISH_AUTH_QA.md",
      }),
      Object.freeze({
        id: "TC-2.02-AC-BOOK-01",
        featureOrBugId: "F-2.02-AC-BOOK-01",
        product: PRODUCTS.AC,
        objective: "AC booking FIXED_PASS",
        prerequisites: "AC booking readiness report",
        steps: ["Confirm FIXED_PASS verdict"],
        expectedResult: "FIXED_PASS recorded",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_01_AC_BOOKING_READINESS_QA.md",
      }),
      Object.freeze({
        id: "TC-2.02-LIMITS-01",
        featureOrBugId: "F-2.02-LIMITS-01",
        product: PRODUCTS.SHARED,
        objective: "Non-claims present in 2.02 notes",
        prerequisites: "Catalog 2.02",
        steps: ["Read pendingDevelopment and knownIssues", "Confirm no production RELEASED claim"],
        expectedResult: "Limitations explicit",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_02_VERSION_RELEASE_NOTES_QA.md",
      }),
      Object.freeze({
        id: "TC-2.02-RNC-01",
        featureOrBugId: "F-2.02-ABOUT-01",
        product: PRODUCTS.SHARED,
        objective: "Release Notes Center serves 2.02 on hub + BB + AC",
        prerequisites: "Deploy containing catalog 2.02",
        steps: [
          "GET hub /release-notes and /release-notes/2.02",
          "GET blessboard /release-notes/2.02",
          "GET activeclinic /release-notes/2.02",
        ],
        expectedResult: "200; 2.02 content; product context preserved",
        status: STATUS.HOSTED_QA_PASS,
        evidence: "docs/qa/V2_02_VERSION_RELEASE_NOTES_QA.md",
      }),
    ],
    sources: [
      "docs/qa/V2_01_P1_RELEASE_GATE_SUMMARY.md",
      "docs/qa/V2_01_P1_BLOCKER_RETEST.md",
      "docs/qa/V2_01_RC_MEDIA_PLACEMENT_FIX_QA.md",
      "docs/qa/V2_01_BB_THEME_503_FIX_QA.md",
      "docs/qa/V2_01_PROD_SHARED_SECURITY_QA.md",
      "docs/qa/V2_01_PROD_PUBLISH_AUTH_QA.md",
      "docs/qa/V2_01_AC_BOOKING_READINESS_QA.md",
      "docs/qa/V2_01_SHARED_THEME_GALLERY_QA.md",
      "docs/qa/V2_01_SHARED_HQ_BRANCH_WEBSITE_QA.md",
      "docs/qa/V2_01_UNIVERSAL_IMAGE_EDITOR_QA.md",
      "docs/qa/V2_02_VERSION_RELEASE_NOTES_QA.md",
    ],
  }),
]);

module.exports = {
  STATUS,
  PRODUCTS,
  VERSION_ORDER,
  VERSIONS,
};
