-- Full PostgreSQL app schema for GetPro (canonical DDL for new databases).
-- Historical note: this file was also the target for the removed SQLite → Postgres copy tooling (`scripts/migrate-sqlite-to-pg/`, since deleted).
-- Apply once on an empty `public` schema (or drop conflicting tables first).
-- Supersedes slice-only DDL such as 001_callback_interests.sql when using this file.
-- Sessions: runtime uses connect-pg-simple (`public.session`) — session table is created/managed by the app, not required as static DDL here.

BEGIN;

CREATE TABLE IF NOT EXISTS public._getpro_migrations (
  id TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tenants (
  id INTEGER PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  stage TEXT NOT NULL DEFAULT 'Enabled',
  callcenter_phone TEXT NOT NULL DEFAULT '+260211000101',
  whatsapp_phone TEXT NOT NULL DEFAULT '+260211000102',
  callcenter_email TEXT NOT NULL DEFAULT 'info@getproapp.org',
  support_help_phone TEXT NOT NULL DEFAULT '+260211000101',
  intake_code_prefix TEXT NOT NULL DEFAULT '',
  phone_strict_validation BOOLEAN NOT NULL DEFAULT false,
  phone_regex TEXT NOT NULL DEFAULT '',
  phone_default_country_code TEXT NOT NULL DEFAULT '',
  phone_normalization_mode TEXT NOT NULL DEFAULT 'generic_digits',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

-- Canonical tenant rows (ids 1–8, global … na) are not INSERTed here; the app inserts missing rows at boot
-- (idempotent ON CONFLICT) so fresh databases satisfy FKs and tenant-scoped admin bootstrap. See tenantsRepo.ensureCanonicalTenantsIfMissing.

CREATE TABLE IF NOT EXISTS public.admin_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'tenant_editor',
  tenant_id INTEGER REFERENCES public.tenants (id),
  enabled BOOLEAN NOT NULL DEFAULT true,
  display_name TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS public.admin_user_tenant_roles (
  admin_user_id INTEGER NOT NULL REFERENCES public.admin_users (id) ON DELETE CASCADE,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  role TEXT NOT NULL,
  PRIMARY KEY (admin_user_id, tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_admin_user_tenant_roles_user ON public.admin_user_tenant_roles (admin_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_user_tenant_roles_tenant ON public.admin_user_tenant_roles (tenant_id);

CREATE TABLE IF NOT EXISTS public.categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  UNIQUE (tenant_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_categories_tenant_sort_name ON public.categories (tenant_id, sort, name);

CREATE TABLE IF NOT EXISTS public.companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  subdomain TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category_id INTEGER REFERENCES public.categories (id) ON DELETE SET NULL,
  headline TEXT NOT NULL DEFAULT '',
  about TEXT NOT NULL DEFAULT '',
  services TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  location TEXT NOT NULL DEFAULT '',
  featured_cta_label TEXT NOT NULL DEFAULT 'Call us',
  featured_cta_phone TEXT NOT NULL DEFAULT '',
  years_experience INTEGER,
  service_areas TEXT NOT NULL DEFAULT '',
  hours_text TEXT NOT NULL DEFAULT '',
  gallery_json TEXT NOT NULL DEFAULT '[]',
  logo_url TEXT NOT NULL DEFAULT '',
  portal_lead_credits_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_companies_tenant_updated_at ON public.companies (tenant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_companies_tenant_name ON public.companies (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_companies_tenant_category ON public.companies (tenant_id, category_id);

CREATE TABLE IF NOT EXISTS public.leads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  company_id INTEGER NOT NULL REFERENCES public.companies (id),
  name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_leads_company_id ON public.leads (company_id);
CREATE INDEX IF NOT EXISTS idx_leads_tenant_created_at ON public.leads (tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_leads_tenant_company_created ON public.leads (tenant_id, company_id, created_at);

CREATE TABLE IF NOT EXISTS public.lead_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id INTEGER NOT NULL REFERENCES public.leads (id) ON DELETE CASCADE,
  body TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_lead_comments_lead_id ON public.lead_comments (lead_id);

CREATE TABLE IF NOT EXISTS public.professional_signups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  profession TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  vat_or_pacra TEXT NOT NULL DEFAULT '',
  converted_company_id INTEGER REFERENCES public.companies (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_professional_signups_tenant_created ON public.professional_signups (tenant_id, created_at);

CREATE TABLE IF NOT EXISTS public.callback_interests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  phone TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  context TEXT NOT NULL DEFAULT '',
  interest_label TEXT NOT NULL DEFAULT 'Potential Partner',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_callback_interests_tenant_created ON public.callback_interests (tenant_id, created_at);

CREATE TABLE IF NOT EXISTS public.reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES public.companies (id) ON DELETE CASCADE,
  rating DOUBLE PRECISION NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  author_name TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CHECK (rating >= 1 AND rating <= 5)
);

CREATE INDEX IF NOT EXISTS idx_reviews_company_created ON public.reviews (company_id, created_at);

CREATE TABLE IF NOT EXISTS public.tenant_cities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  big_city BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (tenant_id, name)
);

CREATE INDEX IF NOT EXISTS idx_tenant_cities_tenant_name ON public.tenant_cities (tenant_id, name);

CREATE TABLE IF NOT EXISTS public.crm_tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  title TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'new',
  owner_id INTEGER REFERENCES public.admin_users (id),
  created_by_id INTEGER REFERENCES public.admin_users (id),
  attachment_url TEXT NOT NULL DEFAULT '',
  source_type TEXT NOT NULL DEFAULT 'manual',
  source_ref_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_crm_tasks_tenant ON public.crm_tasks (tenant_id);
CREATE INDEX IF NOT EXISTS idx_crm_tasks_owner ON public.crm_tasks (owner_id);
CREATE INDEX IF NOT EXISTS idx_crm_tasks_status ON public.crm_tasks (status);

CREATE TABLE IF NOT EXISTS public.crm_audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  task_id INTEGER NOT NULL REFERENCES public.crm_tasks (id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES public.admin_users (id),
  action_type TEXT NOT NULL,
  details TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_crm_audit_task ON public.crm_audit_logs (task_id);
CREATE INDEX IF NOT EXISTS idx_crm_audit_tenant ON public.crm_audit_logs (tenant_id);

CREATE TABLE IF NOT EXISTS public.crm_task_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  task_id INTEGER NOT NULL REFERENCES public.crm_tasks (id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES public.admin_users (id),
  body TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_crm_comments_task ON public.crm_task_comments (task_id);
CREATE INDEX IF NOT EXISTS idx_crm_comments_tenant ON public.crm_task_comments (tenant_id);

CREATE TABLE IF NOT EXISTS public.content_pages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  kind TEXT NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  hero_image_url TEXT NOT NULL DEFAULT '',
  hero_image_alt TEXT NOT NULL DEFAULT '',
  seo_title TEXT NOT NULL DEFAULT '',
  seo_description TEXT NOT NULL DEFAULT '',
  published BOOLEAN NOT NULL DEFAULT false,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  UNIQUE (tenant_id, kind, slug),
  CHECK (kind IN ('article', 'guide', 'faq'))
);

CREATE INDEX IF NOT EXISTS idx_content_pages_tenant_kind ON public.content_pages (tenant_id, kind);
CREATE INDEX IF NOT EXISTS idx_content_pages_published ON public.content_pages (tenant_id, published);
CREATE INDEX IF NOT EXISTS idx_content_pages_tenant_kind_published_sort
  ON public.content_pages (tenant_id, kind, published, sort_order);

CREATE TABLE IF NOT EXISTS public.intake_code_sequences (
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  scope TEXT NOT NULL CHECK (scope IN ('client', 'project')),
  next_seq INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (tenant_id, scope)
);

CREATE TABLE IF NOT EXISTS public.intake_clients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  client_code TEXT NOT NULL,
  external_client_reference TEXT NOT NULL DEFAULT '',
  full_name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  phone_normalized TEXT NOT NULL DEFAULT '',
  whatsapp_phone TEXT NOT NULL DEFAULT '',
  nrz_number TEXT NOT NULL DEFAULT '',
  nrz_normalized TEXT NOT NULL DEFAULT '',
  address_street TEXT NOT NULL DEFAULT '',
  address_house_number TEXT NOT NULL DEFAULT '',
  address_apartment_number TEXT NOT NULL DEFAULT '',
  phone_verified_at TIMESTAMPTZ,
  updated_by_admin_user_id INTEGER REFERENCES public.admin_users (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  UNIQUE (tenant_id, client_code)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_intake_clients_tenant_phone_nonempty
  ON public.intake_clients (tenant_id, phone_normalized)
  WHERE length(trim(phone_normalized)) > 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_intake_clients_tenant_nrz_nonempty
  ON public.intake_clients (tenant_id, nrz_normalized)
  WHERE length(trim(nrz_normalized)) > 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_intake_clients_tenant_extref_nonempty
  ON public.intake_clients (tenant_id, external_client_reference)
  WHERE length(trim(external_client_reference)) > 0;

CREATE TABLE IF NOT EXISTS public.intake_client_projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  client_id INTEGER NOT NULL REFERENCES public.intake_clients (id) ON DELETE CASCADE,
  project_code TEXT NOT NULL,
  client_full_name_snapshot TEXT NOT NULL DEFAULT '',
  client_phone_snapshot TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  neighborhood TEXT NOT NULL DEFAULT '',
  street_name TEXT NOT NULL DEFAULT '',
  house_number TEXT NOT NULL DEFAULT '',
  apartment_number TEXT NOT NULL DEFAULT '',
  client_address_street TEXT NOT NULL DEFAULT '',
  client_address_house_number TEXT NOT NULL DEFAULT '',
  client_address_apartment_number TEXT NOT NULL DEFAULT '',
  estimated_budget_value DOUBLE PRECISION,
  estimated_budget_currency TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'new',
  intake_category_id INTEGER REFERENCES public.categories (id),
  intake_allocation_wave_deadline_at TIMESTAMPTZ,
  intake_allocation_wave_number INTEGER NOT NULL DEFAULT 0,
  intake_auto_allocation_seeded BOOLEAN NOT NULL DEFAULT false,
  intake_auto_allocation_paused BOOLEAN NOT NULL DEFAULT false,
  created_by_admin_user_id INTEGER REFERENCES public.admin_users (id),
  updated_by_admin_user_id INTEGER REFERENCES public.admin_users (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  UNIQUE (tenant_id, project_code)
);

CREATE INDEX IF NOT EXISTS idx_intake_projects_tenant_client ON public.intake_client_projects (tenant_id, client_id);
CREATE INDEX IF NOT EXISTS idx_intake_client_projects_tenant_created ON public.intake_client_projects (tenant_id, created_at);

CREATE TABLE IF NOT EXISTS public.intake_project_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  project_id INTEGER NOT NULL REFERENCES public.intake_client_projects (id) ON DELETE CASCADE,
  image_path TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_intake_project_images_lookup ON public.intake_project_images (tenant_id, project_id, sort_order);

CREATE TABLE IF NOT EXISTS public.intake_phone_otp (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  client_id INTEGER REFERENCES public.intake_clients (id) ON DELETE SET NULL,
  phone_normalized TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  purpose TEXT NOT NULL DEFAULT 'phone_verify',
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 5,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_intake_otp_lookup ON public.intake_phone_otp (tenant_id, phone_normalized, expires_at);

CREATE TABLE IF NOT EXISTS public.intake_category_lead_settings (
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES public.categories (id) ON DELETE CASCADE,
  response_window_hours INTEGER NOT NULL DEFAULT 72,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  PRIMARY KEY (tenant_id, category_id)
);

CREATE TABLE IF NOT EXISTS public.intake_allocation_settings (
  tenant_id INTEGER PRIMARY KEY REFERENCES public.tenants (id) ON DELETE CASCADE,
  established_min_rating DOUBLE PRECISION NOT NULL DEFAULT 3.0,
  established_min_review_count INTEGER NOT NULL DEFAULT 5,
  provisional_min_rating DOUBLE PRECISION NOT NULL DEFAULT 2.0,
  provisional_max_review_count INTEGER NOT NULL DEFAULT 4,
  initial_allocation_count INTEGER NOT NULL DEFAULT 3,
  target_positive_responses INTEGER NOT NULL DEFAULT 2,
  require_category_for_publish BOOLEAN NOT NULL DEFAULT true,
  require_budget_for_publish BOOLEAN NOT NULL DEFAULT true,
  require_min_images_for_publish BOOLEAN NOT NULL DEFAULT true,
  min_images_for_publish INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS public.company_personnel_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  company_id INTEGER NOT NULL REFERENCES public.companies (id),
  full_name TEXT NOT NULL DEFAULT '',
  phone_normalized TEXT NOT NULL DEFAULT '',
  username TEXT NOT NULL DEFAULT '',
  password_hash TEXT NOT NULL DEFAULT '',
  nrz_number TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_company_personnel_tenant_phone_nonempty
  ON public.company_personnel_users (tenant_id, phone_normalized)
  WHERE length(trim(phone_normalized)) > 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_company_personnel_tenant_username_nonempty
  ON public.company_personnel_users (tenant_id, username)
  WHERE length(trim(username)) > 0;

CREATE INDEX IF NOT EXISTS idx_company_personnel_company ON public.company_personnel_users (tenant_id, company_id);

CREATE TABLE IF NOT EXISTS public.intake_project_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  project_id INTEGER NOT NULL REFERENCES public.intake_client_projects (id) ON DELETE CASCADE,
  company_id INTEGER NOT NULL REFERENCES public.companies (id),
  assigned_by_admin_user_id INTEGER REFERENCES public.admin_users (id),
  status TEXT NOT NULL DEFAULT 'pending',
  responded_at TIMESTAMPTZ,
  response_note TEXT NOT NULL DEFAULT '',
  updated_by_company_user_id INTEGER REFERENCES public.company_personnel_users (id),
  response_deadline_at TIMESTAMPTZ,
  allocation_source TEXT NOT NULL DEFAULT 'manual',
  allocation_wave INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  UNIQUE (tenant_id, project_id, company_id)
);

CREATE INDEX IF NOT EXISTS idx_intake_assign_company_status ON public.intake_project_assignments (tenant_id, company_id, status);
CREATE INDEX IF NOT EXISTS idx_intake_assign_project ON public.intake_project_assignments (tenant_id, project_id);

CREATE TABLE IF NOT EXISTS public.company_portal_credit_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  company_id INTEGER NOT NULL REFERENCES public.companies (id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  UNIQUE (tenant_id, company_id)
);

CREATE INDEX IF NOT EXISTS idx_cp_credit_accounts_tenant ON public.company_portal_credit_accounts (tenant_id);

CREATE TABLE IF NOT EXISTS public.company_portal_credit_ledger_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  company_id INTEGER NOT NULL REFERENCES public.companies (id) ON DELETE CASCADE,
  credit_account_id INTEGER NOT NULL REFERENCES public.company_portal_credit_accounts (id) ON DELETE CASCADE,
  amount_zmw DOUBLE PRECISION NOT NULL,
  payment_method TEXT NOT NULL,
  transaction_reference TEXT NOT NULL,
  payment_date TEXT NOT NULL,
  approver_name TEXT NOT NULL,
  recorded_by_admin_user_id INTEGER REFERENCES public.admin_users (id),
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CHECK (amount_zmw > 0)
);

CREATE INDEX IF NOT EXISTS idx_cp_credit_ledger_tenant_co ON public.company_portal_credit_ledger_entries (tenant_id, company_id);
CREATE INDEX IF NOT EXISTS idx_cp_credit_ledger_account ON public.company_portal_credit_ledger_entries (credit_account_id);

COMMIT;
