-- Field Agent: accounts, service provider submissions, callback leads.
-- Apply after 000_full_schema.sql. Idempotent-style CREATE IF NOT EXISTS / indexes.

BEGIN;

CREATE TABLE IF NOT EXISTS public.field_agents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT field_agents_username_tenant_unique UNIQUE (tenant_id, username)
);

CREATE INDEX IF NOT EXISTS idx_field_agents_tenant ON public.field_agents (tenant_id);

-- Submissions by field agents (service provider leads). Status workflow: pending → approved | rejected
CREATE TABLE IF NOT EXISTS public.field_agent_provider_submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  field_agent_id INTEGER NOT NULL REFERENCES public.field_agents (id) ON DELETE CASCADE,
  phone_raw TEXT NOT NULL DEFAULT '',
  phone_norm TEXT NOT NULL DEFAULT '',
  whatsapp_raw TEXT NOT NULL DEFAULT '',
  whatsapp_norm TEXT NOT NULL DEFAULT '',
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  profession TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  pacra TEXT NOT NULL DEFAULT '',
  address_street TEXT NOT NULL DEFAULT '',
  address_landmarks TEXT NOT NULL DEFAULT '',
  address_neighbourhood TEXT NOT NULL DEFAULT '',
  address_city TEXT NOT NULL DEFAULT '',
  nrc_number TEXT NOT NULL DEFAULT '',
  photo_profile_url TEXT NOT NULL DEFAULT '',
  work_photos_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  rejection_reason TEXT NOT NULL DEFAULT '',
  commission_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_fa_sub_tenant_agent ON public.field_agent_provider_submissions (tenant_id, field_agent_id);
CREATE INDEX IF NOT EXISTS idx_fa_sub_status ON public.field_agent_provider_submissions (tenant_id, status);

-- Prevent duplicate active pipeline by normalized phone/whatsapp per tenant (submissions not rejected-only: allow new if previous rejected — use partial unique on pending+approved)
CREATE UNIQUE INDEX IF NOT EXISTS idx_fa_sub_tenant_phone_unique
  ON public.field_agent_provider_submissions (tenant_id, phone_norm)
  WHERE phone_norm <> '' AND status IN ('pending', 'approved');

CREATE UNIQUE INDEX IF NOT EXISTS idx_fa_sub_tenant_wa_unique
  ON public.field_agent_provider_submissions (tenant_id, whatsapp_norm)
  WHERE whatsapp_norm <> '' AND status IN ('pending', 'approved');

CREATE TABLE IF NOT EXISTS public.field_agent_callback_leads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  field_agent_id INTEGER NOT NULL REFERENCES public.field_agents (id) ON DELETE CASCADE,
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  location_city TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_fa_cb_tenant_agent ON public.field_agent_callback_leads (tenant_id, field_agent_id);

COMMIT;
