-- Test fixture registry for Admin > DB seed/clear (runtime gated by src/admin/dbFixturesEnv.js).
-- Apply after 000_full_schema.sql and field_agent DDL.

BEGIN;

CREATE TABLE IF NOT EXISTS public.seed_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_uuid UUID NOT NULL UNIQUE,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  created_by_admin_user_id INTEGER REFERENCES public.admin_users (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_seed_runs_tenant ON public.seed_runs (tenant_id);

CREATE TABLE IF NOT EXISTS public.seed_run_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id INTEGER NOT NULL REFERENCES public.seed_runs (id) ON DELETE CASCADE,
  table_name TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  UNIQUE (run_id, table_name, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_seed_run_items_run ON public.seed_run_items (run_id);

COMMENT ON TABLE public.seed_runs IS 'Registry for admin test-data seed batches (one row per Create Test Data run).';
COMMENT ON TABLE public.seed_run_items IS 'PKs of rows created by a seed run, for FK-safe targeted delete.';

COMMIT;
