-- Post-completion reviews: one row per (assignment, reviewer_role).
-- reviewer_role: 'provider' (SP rates client) or 'client' (client rates SP; may link to public.reviews).

CREATE TABLE IF NOT EXISTS public.intake_deal_reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  project_id INTEGER NOT NULL REFERENCES public.intake_client_projects (id) ON DELETE CASCADE,
  assignment_id INTEGER NOT NULL REFERENCES public.intake_project_assignments (id) ON DELETE CASCADE,
  reviewer_role TEXT NOT NULL CHECK (reviewer_role IN ('provider', 'client')),
  rating DOUBLE PRECISION NOT NULL CHECK (rating >= 1 AND rating <= 5),
  body TEXT NOT NULL DEFAULT '',
  public_review_id INTEGER REFERENCES public.reviews (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  UNIQUE (assignment_id, reviewer_role)
);

CREATE INDEX IF NOT EXISTS idx_intake_deal_reviews_tenant_project
  ON public.intake_deal_reviews (tenant_id, project_id);

CREATE INDEX IF NOT EXISTS idx_intake_deal_reviews_assignment
  ON public.intake_deal_reviews (tenant_id, assignment_id);
