-- Admin draft pay-run snapshots: frozen per-field-agent commission rows for a calendar period.
-- Idempotent-style. Apply after field_agents / tenants / admin_users exist.

BEGIN;

CREATE TABLE IF NOT EXISTS public.field_agent_pay_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'locked', 'approved', 'paid', 'void')),
  created_by_admin_user_id INTEGER REFERENCES public.admin_users (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  notes TEXT NOT NULL DEFAULT '',
  snapshot_version TEXT NOT NULL DEFAULT '1'
);

CREATE UNIQUE INDEX IF NOT EXISTS field_agent_pay_runs_tenant_period_unique
  ON public.field_agent_pay_runs (tenant_id, period_start, period_end);

CREATE INDEX IF NOT EXISTS idx_field_agent_pay_runs_tenant ON public.field_agent_pay_runs (tenant_id);
CREATE INDEX IF NOT EXISTS idx_field_agent_pay_runs_status ON public.field_agent_pay_runs (tenant_id, status);

CREATE TABLE IF NOT EXISTS public.field_agent_pay_run_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pay_run_id INTEGER NOT NULL REFERENCES public.field_agent_pay_runs (id) ON DELETE CASCADE,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  field_agent_id INTEGER NOT NULL REFERENCES public.field_agents (id) ON DELETE CASCADE,
  field_agent_label_snapshot TEXT NOT NULL DEFAULT '',
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  sp_rating_value_used DOUBLE PRECISION,
  sp_rating_low_threshold_used DOUBLE PRECISION NOT NULL,
  sp_rating_high_threshold_used DOUBLE PRECISION NOT NULL,
  sp_high_rating_bonus_percent_used DOUBLE PRECISION,
  earned_sp_commission DOUBLE PRECISION NOT NULL DEFAULT 0,
  sp_bonus_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  sp_withheld_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  sp_payable_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  earned_ec_commission DOUBLE PRECISION NOT NULL DEFAULT 0,
  ec_withheld_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  ec_payable_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  recruitment_commission_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  quality_status_label_sp TEXT NOT NULL DEFAULT '',
  quality_status_label_ec TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_field_agent_pay_run_items_pay_run ON public.field_agent_pay_run_items (pay_run_id);
CREATE INDEX IF NOT EXISTS idx_field_agent_pay_run_items_tenant_fa ON public.field_agent_pay_run_items (tenant_id, field_agent_id);

COMMIT;
