-- Field-agent statement disputes (read-only vs pay-run snapshots; no monetary adjustments in this table).

BEGIN;

CREATE TABLE IF NOT EXISTS public.field_agent_pay_run_disputes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  pay_run_id INTEGER NOT NULL REFERENCES public.field_agent_pay_runs (id) ON DELETE CASCADE,
  pay_run_item_id INTEGER NOT NULL REFERENCES public.field_agent_pay_run_items (id) ON DELETE CASCADE,
  field_agent_id INTEGER NOT NULL REFERENCES public.field_agents (id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'under_review', 'resolved', 'rejected')),
  dispute_reason TEXT NOT NULL,
  dispute_notes TEXT,
  admin_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  resolved_at TIMESTAMPTZ,
  resolved_by_admin_user_id INTEGER REFERENCES public.admin_users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_fa_pay_run_disputes_tenant_fa ON public.field_agent_pay_run_disputes (tenant_id, field_agent_id);
CREATE INDEX IF NOT EXISTS idx_fa_pay_run_disputes_tenant_run ON public.field_agent_pay_run_disputes (tenant_id, pay_run_id);
CREATE INDEX IF NOT EXISTS idx_fa_pay_run_disputes_tenant_item ON public.field_agent_pay_run_disputes (tenant_id, pay_run_item_id);

-- At most one active dispute per line item (open or under review).
CREATE UNIQUE INDEX IF NOT EXISTS field_agent_pay_run_disputes_one_active_per_item
  ON public.field_agent_pay_run_disputes (pay_run_item_id)
  WHERE status IN ('open', 'under_review');

COMMIT;
