-- Ledger-style corrections for field-agent pay runs. Does not modify snapshot rows on field_agent_pay_runs / field_agent_pay_run_items.

BEGIN;

CREATE TABLE IF NOT EXISTS public.field_agent_pay_run_adjustments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  original_pay_run_id INTEGER NOT NULL REFERENCES public.field_agent_pay_runs (id) ON DELETE CASCADE,
  original_pay_run_item_id INTEGER NOT NULL REFERENCES public.field_agent_pay_run_items (id) ON DELETE CASCADE,
  field_agent_id INTEGER NOT NULL REFERENCES public.field_agents (id) ON DELETE CASCADE,
  adjustment_amount NUMERIC(12, 2) NOT NULL,
  adjustment_type TEXT NOT NULL DEFAULT 'manual' CHECK (adjustment_type IN ('sp', 'ec', 'recruitment', 'manual')),
  reason TEXT NOT NULL,
  admin_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  created_by_admin_user_id INTEGER NOT NULL REFERENCES public.admin_users (id) ON DELETE RESTRICT,
  applied_in_pay_run_id INTEGER REFERENCES public.field_agent_pay_runs (id) ON DELETE SET NULL,
  dispute_id INTEGER REFERENCES public.field_agent_pay_run_disputes (id) ON DELETE SET NULL,
  CONSTRAINT field_agent_pay_run_adjustments_amount_nonzero CHECK (adjustment_amount <> 0)
);

CREATE INDEX IF NOT EXISTS idx_fa_pay_run_adj_tenant_fa ON public.field_agent_pay_run_adjustments (tenant_id, field_agent_id);
CREATE INDEX IF NOT EXISTS idx_fa_pay_run_adj_tenant_orig_run ON public.field_agent_pay_run_adjustments (tenant_id, original_pay_run_id);
CREATE INDEX IF NOT EXISTS idx_fa_pay_run_adj_tenant_applied_run ON public.field_agent_pay_run_adjustments (tenant_id, applied_in_pay_run_id);

COMMIT;
