CREATE TABLE IF NOT EXISTS public.admin_field_agent_analytics_presets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  admin_user_id INTEGER NOT NULL REFERENCES public.admin_users (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  record_type TEXT NOT NULL,
  bucket TEXT NOT NULL,
  filters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_faa_presets_tenant_user_type_name
  ON public.admin_field_agent_analytics_presets (tenant_id, admin_user_id, record_type, name);

CREATE INDEX IF NOT EXISTS idx_faa_presets_tenant_user_type
  ON public.admin_field_agent_analytics_presets (tenant_id, admin_user_id, record_type);
