-- Append-only audit trail for field agent submission moderation (tenant-scoped).

CREATE TABLE IF NOT EXISTS public.field_agent_submission_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  submission_id INTEGER NOT NULL REFERENCES public.field_agent_provider_submissions (id) ON DELETE RESTRICT,
  admin_user_id INTEGER NOT NULL REFERENCES public.admin_users (id) ON DELETE RESTRICT,
  action_type TEXT NOT NULL CHECK (action_type IN ('approve', 'reject', 'info_needed', 'appeal')),
  previous_status TEXT NOT NULL,
  new_status TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fasa_tenant_submission_created
  ON public.field_agent_submission_audit (tenant_id, submission_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_fasa_tenant_created
  ON public.field_agent_submission_audit (tenant_id, created_at DESC);
