-- Internal payment ledger rows for pay-run reconciliation (append-only by convention).

BEGIN;

CREATE TABLE IF NOT EXISTS public.field_agent_pay_run_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  pay_run_id INTEGER NOT NULL REFERENCES public.field_agent_pay_runs (id) ON DELETE RESTRICT,
  payment_date DATE NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  payment_method TEXT,
  payment_reference TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_admin_user_id INTEGER REFERENCES public.admin_users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_fapr_payments_tenant_payrun_date
  ON public.field_agent_pay_run_payments (tenant_id, pay_run_id, payment_date DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_fapr_payments_tenant_created
  ON public.field_agent_pay_run_payments (tenant_id, created_at DESC, id DESC);

COMMIT;
