-- Append-only audit trail for pay-run status transitions driven by ledger reconciliation (approved ↔ paid).

BEGIN;

CREATE TABLE IF NOT EXISTS public.field_agent_pay_run_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  pay_run_id INTEGER NOT NULL REFERENCES public.field_agent_pay_runs (id) ON DELETE CASCADE,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  reason TEXT NOT NULL,
  actor_admin_user_id INTEGER REFERENCES public.admin_users (id) ON DELETE SET NULL,
  source_payment_id BIGINT REFERENCES public.field_agent_pay_run_payments (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fapr_status_hist_tenant_payrun
  ON public.field_agent_pay_run_status_history (tenant_id, pay_run_id);

CREATE INDEX IF NOT EXISTS idx_fapr_status_hist_payrun_created
  ON public.field_agent_pay_run_status_history (pay_run_id, created_at);

COMMIT;
