-- Finance-grade point-in-time snapshots for pay runs (e.g. month-close). Does not lock or alter pay runs or ledger rows.

BEGIN;

CREATE TABLE IF NOT EXISTS public.field_agent_pay_run_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  pay_run_id INTEGER NOT NULL REFERENCES public.field_agent_pay_runs (id) ON DELETE CASCADE,
  snapshot_type TEXT NOT NULL,
  frozen_payable NUMERIC(14, 2) NOT NULL,
  net_paid NUMERIC(14, 2) NOT NULL,
  remaining_balance NUMERIC(14, 2) NOT NULL,
  status TEXT NOT NULL,
  snapshot_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor_admin_user_id INTEGER NOT NULL REFERENCES public.admin_users (id) ON DELETE RESTRICT,
  CONSTRAINT field_agent_pay_run_snapshots_type_len CHECK (char_length(snapshot_type) >= 1 AND char_length(snapshot_type) <= 64)
);

CREATE INDEX IF NOT EXISTS idx_fapr_snapshots_tenant_payrun_at
  ON public.field_agent_pay_run_snapshots (tenant_id, pay_run_id, snapshot_at DESC, id DESC);

COMMIT;
