-- Tenant-scoped accounting month locks (YYYY-MM). Pay runs link implicitly via field_agent_pay_runs.period_start (UTC month).

BEGIN;

CREATE TABLE IF NOT EXISTS public.accounting_periods (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  period_id VARCHAR(7) NOT NULL CHECK (period_id ~ '^\d{4}-\d{2}$'),
  is_locked BOOLEAN NOT NULL DEFAULT false,
  locked_at TIMESTAMPTZ,
  locked_by_admin_user_id INTEGER REFERENCES public.admin_users (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  UNIQUE (tenant_id, period_id)
);

CREATE INDEX IF NOT EXISTS idx_accounting_periods_tenant_locked
  ON public.accounting_periods (tenant_id, period_id)
  WHERE is_locked = true;

COMMIT;
