-- Explicit audit trail for finance exceptions (reversal-window bypass, period unlock, future closed-run bypass).
-- Not merged into generic application logs.

BEGIN;

CREATE TABLE IF NOT EXISTS public.finance_override_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  action_type TEXT NOT NULL CHECK (
    action_type IN (
      'reverse_override',
      'correction_override',
      'unlock_period',
      'closed_run_override'
    )
  ),
  reason TEXT NOT NULL,
  actor_admin_user_id INTEGER REFERENCES public.admin_users (id) ON DELETE SET NULL,
  pay_run_id INTEGER REFERENCES public.field_agent_pay_runs (id) ON DELETE SET NULL,
  payment_id BIGINT REFERENCES public.field_agent_pay_run_payments (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_finance_override_events_tenant_created
  ON public.finance_override_events (tenant_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_finance_override_events_action
  ON public.finance_override_events (tenant_id, action_type, created_at DESC);

COMMIT;
