-- Payout batches: group approved-for-payout pay runs for finance operations (no bank execution).

BEGIN;

CREATE TABLE IF NOT EXISTS public.field_agent_payout_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  batch_reference TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed', 'cancelled')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  created_by_admin_user_id INTEGER REFERENCES public.admin_users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS field_agent_payout_batches_tenant_reference_unique
  ON public.field_agent_payout_batches (tenant_id, batch_reference);

CREATE INDEX IF NOT EXISTS idx_field_agent_payout_batches_tenant_created
  ON public.field_agent_payout_batches (tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.field_agent_payout_batch_pay_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payout_batch_id INTEGER NOT NULL REFERENCES public.field_agent_payout_batches (id) ON DELETE CASCADE,
  pay_run_id INTEGER NOT NULL REFERENCES public.field_agent_pay_runs (id) ON DELETE RESTRICT,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  added_by_admin_user_id INTEGER REFERENCES public.admin_users (id) ON DELETE SET NULL,
  UNIQUE (payout_batch_id, pay_run_id)
);

-- Each pay run may appear in at most one batch (closed batches retain history).
CREATE UNIQUE INDEX IF NOT EXISTS field_agent_payout_batch_pay_runs_pay_run_unique
  ON public.field_agent_payout_batch_pay_runs (pay_run_id);

CREATE INDEX IF NOT EXISTS idx_fap_batch_members_batch
  ON public.field_agent_payout_batch_pay_runs (payout_batch_id);

CREATE INDEX IF NOT EXISTS idx_fap_batch_members_tenant
  ON public.field_agent_payout_batch_pay_runs (tenant_id, pay_run_id);

COMMIT;
