-- Append-only finance audit for payout workflow (approval, batching, completion, reconciliation).

BEGIN;

CREATE TABLE IF NOT EXISTS public.field_agent_payout_finance_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES public.tenants (id) ON DELETE CASCADE,
  actor_admin_user_id INTEGER REFERENCES public.admin_users (id) ON DELETE SET NULL,
  action_type TEXT NOT NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('pay_run', 'payout_batch')),
  entity_id INTEGER NOT NULL,
  note TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_fapfa_tenant_entity_created
  ON public.field_agent_payout_finance_audit (tenant_id, entity_type, entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_fapfa_tenant_created
  ON public.field_agent_payout_finance_audit (tenant_id, created_at DESC);

COMMENT ON TABLE public.field_agent_payout_finance_audit IS 'Append-only audit log for payout finance actions; no UPDATE/DELETE.';

COMMIT;
