-- GetPro Church — core MVP tables (Phase 0).
-- Idempotent: safe to run at startup via ensureChurchSchema.

CREATE TABLE IF NOT EXISTS public.church_organizations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform_tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_organizations_slug_unique UNIQUE (slug),
  CONSTRAINT church_organizations_status_check CHECK (status IN ('active', 'inactive', 'suspended'))
);

CREATE INDEX IF NOT EXISTS idx_church_organizations_platform_tenant
  ON public.church_organizations (platform_tenant_id);

CREATE TABLE IF NOT EXISTS public.church_branches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  welcome_message TEXT NOT NULL DEFAULT '',
  service_times TEXT NOT NULL DEFAULT '',
  location_text TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_branches_org_slug_unique UNIQUE (organization_id, slug),
  CONSTRAINT church_branches_status_check CHECK (status IN ('active', 'inactive'))
);

CREATE INDEX IF NOT EXISTS idx_church_branches_organization
  ON public.church_branches (organization_id);

CREATE TABLE IF NOT EXISTS public.church_members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  platform_tenant_id INTEGER NOT NULL REFERENCES public.tenants (id),
  email TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  full_name TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_members_status_check CHECK (status IN ('pending', 'verified', 'rejected', 'inactive'))
);

CREATE INDEX IF NOT EXISTS idx_church_members_branch_status
  ON public.church_members (branch_id, status);

CREATE TABLE IF NOT EXISTS public.church_branch_admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL DEFAULT '',
  display_name TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_branch_admins_branch_username_unique UNIQUE (branch_id, username),
  CONSTRAINT church_branch_admins_status_check CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS public.church_hq_admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL DEFAULT '',
  display_name TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_hq_admins_org_username_unique UNIQUE (organization_id, username),
  CONSTRAINT church_hq_admins_status_check CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS public.church_attendance_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  service_date DATE NOT NULL,
  service_label TEXT NOT NULL DEFAULT '',
  headcount INTEGER NOT NULL DEFAULT 0,
  notes TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'recorded',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_attendance_records_status_check CHECK (status IN ('recorded', 'void'))
);

CREATE INDEX IF NOT EXISTS idx_church_attendance_branch_date
  ON public.church_attendance_records (branch_id, service_date DESC);

CREATE TABLE IF NOT EXISTS public.church_giving_summaries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  period_year INTEGER NOT NULL,
  period_month INTEGER NOT NULL,
  total_amount_cents INTEGER NOT NULL DEFAULT 0,
  currency_code TEXT NOT NULL DEFAULT 'ZMW',
  notes TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_giving_summaries_branch_period_unique UNIQUE (branch_id, period_year, period_month),
  CONSTRAINT church_giving_summaries_status_check CHECK (status IN ('draft', 'finalized'))
);

CREATE TABLE IF NOT EXISTS public.church_monthly_reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  period_year INTEGER NOT NULL,
  period_month INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  summary_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_monthly_reports_branch_period_unique UNIQUE (branch_id, period_year, period_month),
  CONSTRAINT church_monthly_reports_status_check CHECK (
    status IN ('draft', 'submitted', 'approved', 'returned')
  )
);

CREATE TABLE IF NOT EXISTS public.church_audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER REFERENCES public.church_organizations (id) ON DELETE SET NULL,
  branch_id INTEGER REFERENCES public.church_branches (id) ON DELETE SET NULL,
  actor_type TEXT NOT NULL DEFAULT 'system',
  actor_id INTEGER,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL DEFAULT '',
  entity_id INTEGER,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS idx_church_audit_logs_org_created
  ON public.church_audit_logs (organization_id, created_at DESC);
