-- GetPro Church — member portal tables (Phase 6).
-- Idempotent: safe at startup via ensureChurchSchema.

CREATE TABLE IF NOT EXISTS public.church_announcements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'published',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_announcements_status_check CHECK (status IN ('draft', 'published'))
);

CREATE INDEX IF NOT EXISTS idx_church_announcements_branch_published
  ON public.church_announcements (branch_id, published_at DESC);

CREATE TABLE IF NOT EXISTS public.church_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  event_date DATE NOT NULL,
  event_time TEXT NOT NULL DEFAULT '',
  location_text TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'published',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_events_status_check CHECK (status IN ('draft', 'published'))
);

CREATE INDEX IF NOT EXISTS idx_church_events_branch_date
  ON public.church_events (branch_id, event_date ASC);

CREATE TABLE IF NOT EXISTS public.church_member_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES public.church_members (id) ON DELETE CASCADE,
  request_type TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'submitted',
  admin_comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_member_requests_status_check CHECK (
    status IN ('submitted', 'in_review', 'more_info_needed', 'approved', 'rejected', 'completed')
  )
);

CREATE INDEX IF NOT EXISTS idx_church_member_requests_member
  ON public.church_member_requests (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.church_prayer_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES public.church_members (id) ON DELETE CASCADE,
  prayer_topic TEXT NOT NULL DEFAULT '',
  details TEXT NOT NULL DEFAULT '',
  urgency TEXT NOT NULL DEFAULT 'normal',
  privacy_level TEXT NOT NULL DEFAULT 'private_to_pastor',
  status TEXT NOT NULL DEFAULT 'submitted',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_prayer_requests_status_check CHECK (status IN ('submitted', 'reviewed', 'closed')),
  CONSTRAINT church_prayer_requests_privacy_check CHECK (
    privacy_level IN ('private_to_pastor', 'prayer_team', 'anonymous_summary')
  ),
  CONSTRAINT church_prayer_requests_urgency_check CHECK (
    urgency IN ('normal', 'soon', 'urgent')
  )
);

CREATE INDEX IF NOT EXISTS idx_church_prayer_requests_member
  ON public.church_prayer_requests (member_id, created_at DESC);
