-- GetPro Church — branch website content (Phase 9).
-- Idempotent: safe at startup via ensureChurchSchema.

CREATE TABLE IF NOT EXISTS public.church_branch_website_content (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  homepage_hero_title TEXT NOT NULL DEFAULT '',
  homepage_hero_subtitle TEXT NOT NULL DEFAULT '',
  welcome_message TEXT NOT NULL DEFAULT '',
  service_times TEXT NOT NULL DEFAULT '',
  location_text TEXT NOT NULL DEFAULT '',
  about_title TEXT NOT NULL DEFAULT '',
  about_body TEXT NOT NULL DEFAULT '',
  mission_text TEXT NOT NULL DEFAULT '',
  vision_text TEXT NOT NULL DEFAULT '',
  values_text TEXT NOT NULL DEFAULT '',
  leadership_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  ministries_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  contact_phone TEXT NOT NULL DEFAULT '',
  contact_email TEXT NOT NULL DEFAULT '',
  office_hours TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  map_embed_placeholder TEXT NOT NULL DEFAULT '',
  giving_bank_details TEXT NOT NULL DEFAULT '',
  giving_mobile_money TEXT NOT NULL DEFAULT '',
  giving_categories TEXT NOT NULL DEFAULT '',
  giving_instructions TEXT NOT NULL DEFAULT '',
  giving_qr_placeholder TEXT NOT NULL DEFAULT '',
  footer_message TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft',
  last_published_at TIMESTAMPTZ,
  updated_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_branch_website_content_branch_unique UNIQUE (branch_id),
  CONSTRAINT church_branch_website_content_status_check CHECK (status IN ('draft', 'published'))
);

CREATE INDEX IF NOT EXISTS idx_church_branch_website_content_org
  ON public.church_branch_website_content (organization_id);
