-- GetPro Church — branch giving settings (Phase 10).
-- Idempotent: safe at startup via ensureChurchSchema.

CREATE TABLE IF NOT EXISTS public.church_giving_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  bank_name TEXT NOT NULL DEFAULT '',
  account_name TEXT NOT NULL DEFAULT '',
  account_number TEXT NOT NULL DEFAULT '',
  branch_code TEXT NOT NULL DEFAULT '',
  swift_code TEXT,
  mobile_money_provider_1 TEXT NOT NULL DEFAULT '',
  mobile_money_number_1 TEXT NOT NULL DEFAULT '',
  mobile_money_name_1 TEXT NOT NULL DEFAULT '',
  mobile_money_provider_2 TEXT,
  mobile_money_number_2 TEXT,
  mobile_money_name_2 TEXT,
  giving_categories_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  giving_instructions TEXT NOT NULL DEFAULT '',
  qr_code_label TEXT,
  finance_contact_name TEXT,
  finance_contact_phone TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  updated_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_giving_settings_branch_unique UNIQUE (branch_id),
  CONSTRAINT church_giving_settings_status_check CHECK (status IN ('draft', 'published'))
);

CREATE INDEX IF NOT EXISTS idx_church_giving_settings_branch_status
  ON public.church_giving_settings (branch_id, status);
