-- GetPro Church — ministries, departments, member ministries (Phase 11).
-- Idempotent: safe at startup via ensureChurchSchema.

CREATE TABLE IF NOT EXISTS public.church_ministries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  slug TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  leader_name TEXT NOT NULL DEFAULT '',
  leader_phone TEXT,
  meeting_day TEXT,
  meeting_time TEXT,
  location TEXT,
  visibility TEXT NOT NULL DEFAULT 'members',
  status TEXT NOT NULL DEFAULT 'draft',
  created_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  updated_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_ministries_branch_slug_unique UNIQUE (branch_id, slug),
  CONSTRAINT church_ministries_status_check CHECK (status IN ('draft', 'published', 'archived')),
  CONSTRAINT church_ministries_visibility_check CHECK (visibility IN ('public', 'members', 'leaders'))
);

CREATE INDEX IF NOT EXISTS idx_church_ministries_branch_status
  ON public.church_ministries (branch_id, status);

CREATE TABLE IF NOT EXISTS public.church_departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  slug TEXT NOT NULL DEFAULT '',
  purpose TEXT NOT NULL DEFAULT '',
  leader_name TEXT NOT NULL DEFAULT '',
  leader_phone TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  updated_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_departments_branch_slug_unique UNIQUE (branch_id, slug),
  CONSTRAINT church_departments_status_check CHECK (status IN ('active', 'archived'))
);

CREATE INDEX IF NOT EXISTS idx_church_departments_branch_status
  ON public.church_departments (branch_id, status);

CREATE TABLE IF NOT EXISTS public.church_member_ministries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES public.church_members (id) ON DELETE CASCADE,
  ministry_id INTEGER NOT NULL REFERENCES public.church_ministries (id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member',
  status TEXT NOT NULL DEFAULT 'interested',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_member_ministries_unique UNIQUE (member_id, ministry_id),
  CONSTRAINT church_member_ministries_status_check CHECK (status IN ('interested', 'active', 'inactive'))
);

CREATE INDEX IF NOT EXISTS idx_church_member_ministries_ministry
  ON public.church_member_ministries (ministry_id, status);
