-- GetPro Church — duty roster (Phase 12).
-- Idempotent: safe at startup via ensureChurchSchema.

CREATE TABLE IF NOT EXISTS public.church_duty_roster (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  duty_date DATE NOT NULL,
  service_name TEXT NOT NULL DEFAULT '',
  role_name TEXT NOT NULL DEFAULT '',
  assigned_member_id INTEGER REFERENCES public.church_members (id) ON DELETE SET NULL,
  assigned_member_name TEXT,
  ministry_id INTEGER REFERENCES public.church_ministries (id) ON DELETE SET NULL,
  department_id INTEGER REFERENCES public.church_departments (id) ON DELETE SET NULL,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  created_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  updated_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_duty_roster_status_check CHECK (status IN ('draft', 'confirmed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_church_duty_roster_branch_date
  ON public.church_duty_roster (branch_id, duty_date);

CREATE INDEX IF NOT EXISTS idx_church_duty_roster_branch_status
  ON public.church_duty_roster (branch_id, status);

CREATE INDEX IF NOT EXISTS idx_church_duty_roster_assigned_member
  ON public.church_duty_roster (assigned_member_id);
