-- GetPro Church — ministry leaders and activity notes (Phase 13).
-- Idempotent: safe at startup via ensureChurchSchema.

CREATE TABLE IF NOT EXISTS public.church_ministry_leaders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  ministry_id INTEGER REFERENCES public.church_ministries (id) ON DELETE SET NULL,
  department_id INTEGER REFERENCES public.church_departments (id) ON DELETE SET NULL,
  member_id INTEGER REFERENCES public.church_members (id) ON DELETE SET NULL,
  full_name TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  phone TEXT,
  phone_normalized TEXT,
  password_hash TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'ministry_leader',
  status TEXT NOT NULL DEFAULT 'active',
  created_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_ministry_leaders_role_check CHECK (role IN ('ministry_leader', 'department_leader')),
  CONSTRAINT church_ministry_leaders_status_check CHECK (status IN ('active', 'inactive'))
);

CREATE INDEX IF NOT EXISTS idx_church_ministry_leaders_branch_status
  ON public.church_ministry_leaders (branch_id, status);

CREATE INDEX IF NOT EXISTS idx_church_ministry_leaders_ministry
  ON public.church_ministry_leaders (ministry_id, status);

CREATE TABLE IF NOT EXISTS public.church_ministry_activity_notes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  ministry_id INTEGER REFERENCES public.church_ministries (id) ON DELETE SET NULL,
  department_id INTEGER REFERENCES public.church_departments (id) ON DELETE SET NULL,
  leader_id INTEGER NOT NULL REFERENCES public.church_ministry_leaders (id) ON DELETE CASCADE,
  period_month TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  activity_summary TEXT NOT NULL DEFAULT '',
  challenges TEXT NOT NULL DEFAULT '',
  support_needed TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_ministry_activity_notes_status_check CHECK (status IN ('draft', 'submitted')),
  CONSTRAINT church_ministry_activity_notes_leader_period_unique UNIQUE (leader_id, period_month)
);

CREATE INDEX IF NOT EXISTS idx_church_ministry_activity_notes_ministry
  ON public.church_ministry_activity_notes (ministry_id, period_month);

ALTER TABLE public.church_attendance_records
  ADD COLUMN IF NOT EXISTS ministry_id INTEGER REFERENCES public.church_ministries (id) ON DELETE SET NULL;

ALTER TABLE public.church_attendance_records
  ADD COLUMN IF NOT EXISTS created_by_leader_id INTEGER REFERENCES public.church_ministry_leaders (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_church_attendance_ministry
  ON public.church_attendance_records (branch_id, ministry_id);

CREATE INDEX IF NOT EXISTS idx_church_attendance_leader
  ON public.church_attendance_records (created_by_leader_id);
