-- GetPro Church — ministry join requests (Phase 16).
-- Idempotent: safe at startup via ensureChurchSchema.

CREATE TABLE IF NOT EXISTS public.church_ministry_join_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES public.church_members (id) ON DELETE CASCADE,
  ministry_id INTEGER NOT NULL REFERENCES public.church_ministries (id) ON DELETE CASCADE,
  message TEXT,
  status TEXT NOT NULL DEFAULT 'submitted',
  admin_comment TEXT,
  reviewed_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_ministry_join_requests_status_check CHECK (
    status IN ('submitted', 'approved', 'rejected', 'more_info_needed')
  )
);

CREATE INDEX IF NOT EXISTS idx_church_ministry_join_requests_branch_status
  ON public.church_ministry_join_requests (branch_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_church_ministry_join_requests_member
  ON public.church_ministry_join_requests (member_id, ministry_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_church_ministry_join_requests_open_unique
  ON public.church_ministry_join_requests (member_id, ministry_id)
  WHERE status IN ('submitted', 'more_info_needed');
