-- BlessBoard — public sermons and member resources (idempotent).

CREATE TABLE IF NOT EXISTS public.church_sermons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  speaker TEXT NOT NULL DEFAULT '',
  sermon_date DATE,
  description TEXT NOT NULL DEFAULT '',
  media_url TEXT,
  scripture TEXT,
  category TEXT NOT NULL DEFAULT 'Sunday Sermon',
  status TEXT NOT NULL DEFAULT 'draft',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  updated_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_sermons_status_check CHECK (status IN ('draft', 'published'))
);

CREATE INDEX IF NOT EXISTS idx_church_sermons_branch_status
  ON public.church_sermons (branch_id, status, sermon_date DESC NULLS LAST, sort_order);

CREATE TABLE IF NOT EXISTS public.church_resources (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  resource_type TEXT NOT NULL DEFAULT 'study',
  file_url TEXT,
  external_url TEXT,
  visibility TEXT NOT NULL DEFAULT 'members',
  status TEXT NOT NULL DEFAULT 'draft',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  updated_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_resources_type_check CHECK (resource_type IN ('study', 'document', 'form')),
  CONSTRAINT church_resources_visibility_check CHECK (visibility IN ('public', 'members')),
  CONSTRAINT church_resources_status_check CHECK (status IN ('draft', 'published'))
);

CREATE INDEX IF NOT EXISTS idx_church_resources_branch_status
  ON public.church_resources (branch_id, status, resource_type, sort_order);
