-- BlessBoard operational readiness: member registration flag + public contact submissions.
-- Idempotent: safe at startup via ensureChurchSchema.

ALTER TABLE public.church_branches
  ADD COLUMN IF NOT EXISTS member_registration_enabled BOOLEAN NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS public.church_public_contact_submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE CASCADE,
  full_name TEXT NOT NULL DEFAULT '',
  email TEXT,
  phone TEXT,
  message TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'new',
  reviewed_by_admin_id INTEGER REFERENCES public.church_branch_admins (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT church_public_contact_submissions_status_check
    CHECK (status IN ('new', 'read', 'resolved'))
);

CREATE INDEX IF NOT EXISTS idx_church_public_contact_submissions_branch
  ON public.church_public_contact_submissions (branch_id, status, created_at DESC);
