-- BlessBoard platform public inquiries (contact + church access requests).
-- Apex-only; not tied to church org/branch FKs.

CREATE TABLE IF NOT EXISTS public.church_platform_inquiries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_type TEXT NOT NULL CHECK (inquiry_type IN ('contact', 'register_church')),
  full_name TEXT NOT NULL DEFAULT '',
  email TEXT,
  phone TEXT,
  whatsapp TEXT,
  church_name TEXT,
  branch_name TEXT,
  city TEXT,
  country TEXT,
  role_in_church TEXT,
  branch_count TEXT,
  subject TEXT,
  message TEXT NOT NULL DEFAULT '',
  consent_contact BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'closed')),
  source_ip TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_church_platform_inquiries_status_created
  ON public.church_platform_inquiries (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_church_platform_inquiries_type_created
  ON public.church_platform_inquiries (inquiry_type, created_at DESC);
