-- Growth branch path support: member transfer history preserves prior branch identity.
-- Branch path slugs use existing church_branches.slug (UNIQUE per organization).

CREATE TABLE IF NOT EXISTS public.church_member_branch_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES public.church_organizations (id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES public.church_members (id) ON DELETE CASCADE,
  from_branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE RESTRICT,
  to_branch_id INTEGER NOT NULL REFERENCES public.church_branches (id) ON DELETE RESTRICT,
  transferred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  transferred_by_actor_type TEXT NOT NULL DEFAULT 'hq_admin',
  transferred_by_actor_id INTEGER,
  reason TEXT,
  previous_status TEXT,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT church_member_branch_history_branches_distinct CHECK (from_branch_id <> to_branch_id)
);

CREATE INDEX IF NOT EXISTS idx_church_member_branch_history_member
  ON public.church_member_branch_history (member_id, transferred_at DESC);

CREATE INDEX IF NOT EXISTS idx_church_member_branch_history_org
  ON public.church_member_branch_history (organization_id, transferred_at DESC);
