"use strict";

/**
 * Representative V4 fixture seed for local migration rehearsal.
 * Sanitized synthetic data only — no production PII.
 */

const HASH = "$2a$10$abcdefghijklmnopqrstuv";

/**
 * Expand V4 schema with content/audit tables used by extractors.
 * @param {import('pg').Pool} pool
 */
async function installRehearsalV4Extras(pool) {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS public.church_ministries (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER NOT NULL,
      branch_id INTEGER,
      name TEXT NOT NULL,
      slug TEXT,
      description TEXT,
      status TEXT NOT NULL DEFAULT 'draft'
    );
    CREATE TABLE IF NOT EXISTS public.church_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER NOT NULL,
      branch_id INTEGER,
      title TEXT NOT NULL,
      description TEXT,
      status TEXT NOT NULL DEFAULT 'draft',
      starts_at TIMESTAMPTZ,
      ends_at TIMESTAMPTZ,
      location_text TEXT,
      registration_form_id INTEGER
    );
    CREATE TABLE IF NOT EXISTS public.church_announcements (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER NOT NULL,
      branch_id INTEGER,
      title TEXT NOT NULL,
      body TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'draft',
      published_at TIMESTAMPTZ,
      is_pinned BOOLEAN DEFAULT false,
      is_featured BOOLEAN DEFAULT false,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS public.church_audit_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER,
      branch_id INTEGER,
      actor_type TEXT NOT NULL DEFAULT 'system',
      actor_id INTEGER,
      action TEXT NOT NULL,
      entity_type TEXT NOT NULL DEFAULT '',
      entity_id INTEGER,
      metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
}

/**
 * Seed a multi-tenant representative V4 dataset.
 * Returns expected reconciliation expectations (eligible vs quarantine).
 * @param {import('pg').Pool} pool
 */
async function seedRepresentativeV4(pool) {
  await pool.query(`INSERT INTO public.tenants (slug) VALUES ('rehearsal-a'), ('rehearsal-b')`);
  const tenants = await pool.query(`SELECT id, slug FROM public.tenants ORDER BY id`);
  const tA = tenants.rows.find((r) => r.slug === "rehearsal-a").id;
  const tB = tenants.rows.find((r) => r.slug === "rehearsal-b").id;

  // Org A — clean migrate path (growth)
  const orgA = await pool.query(
    `INSERT INTO public.church_organizations
       (platform_tenant_id, slug, name, status, plan_code, data_environment, legal_name)
     VALUES ($1, 'grace-chapel', 'Grace Chapel', 'active', 'growth', 'pilot', 'Grace Chapel Trust')
     RETURNING id`,
    [tA]
  );
  const orgAId = orgA.rows[0].id;

  // Org B — valid key, free plan
  const orgB = await pool.query(
    `INSERT INTO public.church_organizations
       (platform_tenant_id, slug, name, status, plan_code, data_environment)
     VALUES ($1, 'hope-centre', 'Hope Centre', 'active', 'free', 'testing')
     RETURNING id`,
    [tB]
  );
  const orgBId = orgB.rows[0].id;

  // Org C — invalid slug → expected quarantine (not silent loss)
  await pool.query(
    `INSERT INTO public.church_organizations
       (platform_tenant_id, slug, name, status, plan_code, data_environment)
     VALUES ($1, 'BAD ORG!', 'Bad Org', 'active', 'free', 'pilot')`,
    [tA]
  );

  const hqA = await pool.query(
    `INSERT INTO public.church_branches
       (organization_id, slug, name, status, host_slug, welcome_message, timezone, country_code)
     VALUES ($1, 'hq', 'Headquarters', 'active', 'grace-chapel', 'Welcome', 'Africa/Lusaka', 'ZM')
     RETURNING id`,
    [orgAId]
  );
  const kafue = await pool.query(
    `INSERT INTO public.church_branches
       (organization_id, slug, name, status, host_slug, timezone, country_code)
     VALUES ($1, 'kafue', 'Kafue Campus', 'active', 'grace-kafue', 'Africa/Lusaka', 'ZM')
     RETURNING id`,
    [orgAId]
  );
  const hqB = await pool.query(
    `INSERT INTO public.church_branches
       (organization_id, slug, name, status, host_slug)
     VALUES ($1, 'hq', 'Hope HQ', 'active', 'hope-centre')
     RETURNING id`,
    [orgBId]
  );

  await pool.query(
    `INSERT INTO public.church_hq_admins
       (organization_id, username, password_hash, display_name, status, email)
     VALUES
       ($1, 'hq.grace', $3, 'Grace HQ Admin', 'active', 'hq@grace.example'),
       ($2, 'hq.hope', $3, 'Hope HQ Admin', 'active', 'hq@hope.example')`,
    [orgAId, orgBId, HASH]
  );

  await pool.query(
    `INSERT INTO public.church_branch_admins
       (organization_id, branch_id, username, password_hash, display_name, status, email)
     VALUES ($1, $2, 'kafue.admin', $3, 'Kafue Admin', 'active', 'kafue@grace.example')`,
    [orgAId, kafue.rows[0].id, HASH]
  );
  // Username-only admin → synthesized email warning path
  await pool.query(
    `INSERT INTO public.church_branch_admins
       (organization_id, branch_id, username, password_hash, display_name, status)
     VALUES ($1, $2, 'noemail', $3, 'No Email Admin', 'active')`,
    [orgAId, kafue.rows[0].id, HASH]
  );

  await pool.query(
    `INSERT INTO public.church_members
       (organization_id, branch_id, email, phone, full_name, status, password_hash)
     VALUES
       ($1, $2, 'alice@example.com', '+260971234567', 'Alice Mulenga', 'verified', $4),
       ($1, $2, 'bob@example.com', '+260977654321', 'Bob Banda', 'pending', NULL),
       ($1, $3, 'cara@example.com', '', 'Cara Phiri', 'verified', NULL),
       ($5, $6, 'dan@hope.example', '+260960000001', 'Dan Hope', 'verified', NULL),
       ($1, $2, '', '', 'No Contact Person', 'pending', NULL)`,
    [orgAId, kafue.rows[0].id, hqA.rows[0].id, HASH, orgBId, hqB.rows[0].id]
  );

  await pool.query(
    `INSERT INTO public.church_ministries (organization_id, branch_id, name, slug, description, status)
     VALUES
       ($1, $2, 'Youth Ministry', 'youth', 'Youth fellowship', 'published'),
       ($1, $2, 'Worship', 'worship', 'Worship team', 'draft')`,
    [orgAId, kafue.rows[0].id]
  );

  await pool.query(
    `INSERT INTO public.church_events
       (organization_id, branch_id, title, description, status, starts_at, ends_at, location_text)
     VALUES
       ($1, $2, 'Easter Service', 'Celebration', 'published', '2026-04-05T09:00:00Z', '2026-04-05T11:00:00Z', 'Main Hall'),
       ($1, $2, 'Draft Meetup', NULL, 'draft', '2026-05-01T18:00:00Z', NULL, NULL)`,
    [orgAId, kafue.rows[0].id]
  );

  await pool.query(
    `INSERT INTO public.church_announcements
       (organization_id, branch_id, title, body, status, published_at, is_pinned)
     VALUES
       ($1, $2, 'Welcome Sunday', 'Join us this week.', 'published', '2026-01-01T00:00:00Z', true),
       ($1, NULL, 'HQ Notice', 'Church-wide notice.', 'draft', NULL, false)`,
    [orgAId, kafue.rows[0].id]
  );

  await pool.query(
    `INSERT INTO public.church_attendance_records
       (organization_id, branch_id, service_date, service_label, headcount, status, updated_at)
     VALUES
       ($1, $2, '2026-01-05', 'Sunday Service', 120, 'recorded', now()),
       ($1, $2, '2026-01-12', 'Sunday Service', 98, 'recorded', now()),
       ($1, $2, '2026-01-19', 'Voided', 10, 'void', now())`,
    [orgAId, kafue.rows[0].id]
  );

  await pool.query(
    `INSERT INTO public.church_giving_summaries
       (organization_id, branch_id, period_year, period_month, total_amount_cents, currency_code, status, updated_at)
     VALUES
       ($1, $2, 2026, 1, 125050, 'ZMW', 'finalized', now()),
       ($1, $2, 2026, 2, 50000, 'ZMW', 'draft', now())`,
    [orgAId, kafue.rows[0].id]
  );

  await pool.query(
    `INSERT INTO public.church_audit_logs
       (organization_id, branch_id, actor_type, actor_id, action, entity_type, entity_id, metadata_json)
     VALUES
       ($1, $2, 'hq_admin', 1, 'member.approved', 'member', 1,
        '{"member_id":1,"password":"secret","note":"ok"}'::jsonb),
       ($1, $2, 'system', NULL, 'settings.updated', 'branch', 2,
        '{"field":"timezone"}'::jsonb)`,
    [orgAId, kafue.rows[0].id]
  );

  return {
    orgAId,
    orgBId,
    hqAId: hqA.rows[0].id,
    kafueId: kafue.rows[0].id,
    hqBId: hqB.rows[0].id,
    expectations: {
      organizations: {
        source: 3,
        eligible: 2, // grace-chapel, hope-centre
        quarantine: 1, // BAD ORG!
      },
      branches: { source: 3, eligible: 3 },
      domains: { source: 3, eligible: 3 }, // all have host_slug
      hqAdmins: { source: 2, eligible: 2 },
      branchAdmins: { source: 2, eligible: 2 },
      members: { source: 5, eligible: 4, quarantine: 1 }, // no contact
      ministries: { source: 2, eligible: 2 },
      events: { source: 2, eligible: 2 },
      announcements: { source: 2, eligible: 2 },
      attendance: { source: 3, eligible: 3 },
      giving: { source: 2, eligible: 2 },
      audit: { source: 2, eligible: 2 },
    },
  };
}

module.exports = {
  installRehearsalV4Extras,
  seedRepresentativeV4,
  HASH,
};
