"use strict";

/**
 * Dual local PostgreSQL helpers for V4→V5 migration tooling tests.
 * Never logs credentials. Never uses hosted URLs.
 */

const { Pool, Client } = require("pg");
const { migrate } = require("../../db/scripts/lib/migrator");
const { ensureDatabaseIdentity } = require("../../db/scripts/lib/databaseIdentity");

const SRC_DB = "blessboard_v4_migration_src";
const TGT_DB = "blessboard_v5_migration_tgt";

function adminConnectionString() {
  return (
    process.env.FOUNDATION_ADMIN_DATABASE_URL ||
    process.env.DATABASE_URL_ADMIN ||
    "postgresql://localhost:5432/postgres"
  );
}

function urlFor(dbName) {
  return `postgresql://localhost:5432/${dbName}`;
}

async function recreateDatabase(dbName) {
  const client = new Client({ connectionString: adminConnectionString() });
  await client.connect();
  try {
    await client.query(
      `SELECT pg_terminate_backend(pid)
         FROM pg_stat_activity
        WHERE datname = $1 AND pid <> pg_backend_pid()`,
      [dbName]
    );
    await client.query(`DROP DATABASE IF EXISTS ${dbName}`);
    await client.query(`CREATE DATABASE ${dbName}`);
  } finally {
    await client.end();
  }
  return urlFor(dbName);
}

/**
 * Minimal V4-shaped tables for fixture migration tests.
 * @param {import('pg').Pool} pool
 */
async function installMinimalV4Schema(pool) {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS public.tenants (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      slug TEXT NOT NULL UNIQUE
    );
    CREATE TABLE IF NOT EXISTS public.church_organizations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      platform_tenant_id INTEGER NOT NULL REFERENCES public.tenants(id),
      slug TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'active',
      plan_code TEXT NOT NULL DEFAULT 'free',
      data_environment TEXT,
      legal_name TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS public.church_branches (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER NOT NULL REFERENCES public.church_organizations(id),
      slug TEXT NOT NULL,
      name TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'active',
      host_slug TEXT,
      welcome_message TEXT DEFAULT '',
      service_times TEXT DEFAULT '',
      location_text TEXT DEFAULT '',
      timezone TEXT,
      country_code TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE (organization_id, slug)
    );
    CREATE TABLE IF NOT EXISTS public.church_hq_admins (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER NOT NULL REFERENCES public.church_organizations(id),
      username TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      display_name TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'active',
      email TEXT
    );
    CREATE TABLE IF NOT EXISTS public.church_branch_admins (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER NOT NULL REFERENCES public.church_organizations(id),
      branch_id INTEGER NOT NULL REFERENCES public.church_branches(id),
      username TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      display_name TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'active',
      email TEXT
    );
    CREATE TABLE IF NOT EXISTS public.church_members (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER NOT NULL REFERENCES public.church_organizations(id),
      branch_id INTEGER NOT NULL REFERENCES public.church_branches(id),
      email TEXT NOT NULL DEFAULT '',
      phone TEXT NOT NULL DEFAULT '',
      full_name TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'pending',
      password_hash TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS public.church_attendance_records (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER NOT NULL,
      branch_id INTEGER NOT NULL,
      service_date DATE NOT NULL,
      service_label TEXT NOT NULL DEFAULT '',
      headcount INTEGER NOT NULL DEFAULT 0,
      notes TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'recorded',
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS public.church_giving_summaries (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id INTEGER NOT NULL,
      branch_id INTEGER NOT NULL,
      period_year INTEGER NOT NULL,
      period_month INTEGER NOT NULL,
      total_amount_cents INTEGER NOT NULL DEFAULT 0,
      currency_code TEXT NOT NULL DEFAULT 'ZMW',
      notes TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'draft',
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
}

async function seedMinimalV4(pool) {
  await pool.query(`INSERT INTO public.tenants (slug) VALUES ('grace') RETURNING id`);
  const tenant = await pool.query(`SELECT id FROM public.tenants WHERE slug = 'grace'`);
  const tenantId = tenant.rows[0].id;
  const org = await pool.query(
    `INSERT INTO public.church_organizations
       (platform_tenant_id, slug, name, status, plan_code, data_environment)
     VALUES ($1, 'grace-chapel', 'Grace Chapel', 'active', 'growth', 'pilot')
     RETURNING id`,
    [tenantId]
  );
  const orgId = org.rows[0].id;
  const hq = await pool.query(
    `INSERT INTO public.church_branches
       (organization_id, slug, name, status, host_slug)
     VALUES ($1, 'hq', 'Headquarters', 'active', 'grace-chapel')
     RETURNING id`,
    [orgId]
  );
  const branch = await pool.query(
    `INSERT INTO public.church_branches
       (organization_id, slug, name, status, host_slug)
     VALUES ($1, 'kafue', 'Kafue', 'active', 'grace-kafue')
     RETURNING id`,
    [orgId]
  );
  await pool.query(
    `INSERT INTO public.church_hq_admins
       (organization_id, username, password_hash, display_name, status, email)
     VALUES ($1, 'hqadmin', '$2a$10$abcdefghijklmnopqrstuv', 'HQ Admin', 'active', 'hq@grace.example')`,
    [orgId]
  );
  await pool.query(
    `INSERT INTO public.church_members
       (organization_id, branch_id, email, phone, full_name, status)
     VALUES ($1, $2, 'alice@example.com', '+260971234567', 'Alice Mulenga', 'verified')`,
    [orgId, branch.rows[0].id]
  );
  await pool.query(
    `INSERT INTO public.church_attendance_records
       (organization_id, branch_id, service_date, service_label, headcount, status, updated_at)
     VALUES ($1, $2, '2026-01-05', 'Sunday', 42, 'recorded', now())`,
    [orgId, branch.rows[0].id]
  );
  await pool.query(
    `INSERT INTO public.church_giving_summaries
       (organization_id, branch_id, period_year, period_month, total_amount_cents, currency_code, status, updated_at)
     VALUES ($1, $2, 2026, 1, 10050, 'ZMW', 'finalized', now())`,
    [orgId, branch.rows[0].id]
  );
  return { orgId, hqId: hq.rows[0].id, branchId: branch.rows[0].id };
}

/**
 * Prepare source + target local DBs for tooling tests.
 */
async function prepareMigrationFixtureDatabases(identityKey = "blessboard-platform-v5") {
  const sourceUrl = await recreateDatabase(SRC_DB);
  const targetUrl = await recreateDatabase(TGT_DB);

  const sourcePool = new Pool({ connectionString: sourceUrl, max: 4 });
  const targetPool = new Pool({ connectionString: targetUrl, max: 4 });

  await installMinimalV4Schema(sourcePool);
  await seedMinimalV4(sourcePool);

  await migrate({ connectionString: targetUrl });
  await ensureDatabaseIdentity(targetPool, {
    connectionString: targetUrl,
    identityKey,
    environmentCode: "testing",
  });

  return { sourceUrl, targetUrl, sourcePool, targetPool, identityKey };
}

async function endPools(...pools) {
  for (const p of pools) {
    if (p) await p.end().catch(() => {});
  }
}

module.exports = {
  SRC_DB,
  TGT_DB,
  urlFor,
  recreateDatabase,
  installMinimalV4Schema,
  seedMinimalV4,
  prepareMigrationFixtureDatabases,
  endPools,
};
